

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(957, 391)
        Dialog.setSizeGripEnabled(True)
        self.getFromBoardBu = QtWidgets.QPushButton(Dialog)
        self.getFromBoardBu.setGeometry(QtCore.QRect(20, 360, 91, 23))
        self.getFromBoardBu.setObjectName("getFromBoardBu")
        self.saveToBoardBu = QtWidgets.QPushButton(Dialog)
        self.saveToBoardBu.setGeometry(QtCore.QRect(130, 360, 91, 23))
        self.saveToBoardBu.setObjectName("saveToBoardBu")
        self.exitBu = QtWidgets.QPushButton(Dialog)
        self.exitBu.setGeometry(QtCore.QRect(800, 360, 91, 21))
        self.exitBu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.exitBu.setStyleSheet("")
        self.exitBu.setObjectName("exitBu")
        self.ModuleTemp_Ch = QtWidgets.QCheckBox(Dialog)
        self.ModuleTemp_Ch.setGeometry(QtCore.QRect(890, 50, 21, 17))
        self.ModuleTemp_Ch.setText("")
        self.ModuleTemp_Ch.setChecked(True)
        self.ModuleTemp_Ch.setObjectName("ModuleTemp_Ch")
        self.TEC_I_MON_Ch = QtWidgets.QCheckBox(Dialog)
        self.TEC_I_MON_Ch.setGeometry(QtCore.QRect(890, 80, 21, 17))
        self.TEC_I_MON_Ch.setText("")
        self.TEC_I_MON_Ch.setChecked(True)
        self.TEC_I_MON_Ch.setObjectName("TEC_I_MON_Ch")
        self.Laser_Temp_Ch = QtWidgets.QCheckBox(Dialog)
        self.Laser_Temp_Ch.setGeometry(QtCore.QRect(890, 110, 21, 17))
        self.Laser_Temp_Ch.setText("")
        self.Laser_Temp_Ch.setChecked(True)
        self.Laser_Temp_Ch.setObjectName("Laser_Temp_Ch")
        self.Input_RF_MON_Ch = QtWidgets.QCheckBox(Dialog)
        self.Input_RF_MON_Ch.setGeometry(QtCore.QRect(890, 140, 21, 17))
        self.Input_RF_MON_Ch.setText("")
        self.Input_RF_MON_Ch.setChecked(True)
        self.Input_RF_MON_Ch.setObjectName("Input_RF_MON_Ch")
        self.FLSR_BIAS_Ch = QtWidgets.QCheckBox(Dialog)
        self.FLSR_BIAS_Ch.setGeometry(QtCore.QRect(890, 200, 21, 17))
        self.FLSR_BIAS_Ch.setText("")
        self.FLSR_BIAS_Ch.setChecked(True)
        self.FLSR_BIAS_Ch.setObjectName("FLSR_BIAS_Ch")
        self.LAS_RF_Ch = QtWidgets.QCheckBox(Dialog)
        self.LAS_RF_Ch.setGeometry(QtCore.QRect(890, 170, 21, 17))
        self.LAS_RF_Ch.setText("")
        self.LAS_RF_Ch.setChecked(True)
        self.LAS_RF_Ch.setObjectName("LAS_RF_Ch")
        self.v5_Ch = QtWidgets.QCheckBox(Dialog)
        self.v5_Ch.setGeometry(QtCore.QRect(890, 290, 21, 17))
        self.v5_Ch.setText("")
        self.v5_Ch.setChecked(True)
        self.v5_Ch.setObjectName("v5_Ch")
        self.RLSR_BIAS_Ch = QtWidgets.QCheckBox(Dialog)
        self.RLSR_BIAS_Ch.setGeometry(QtCore.QRect(890, 230, 21, 17))
        self.RLSR_BIAS_Ch.setText("")
        self.RLSR_BIAS_Ch.setChecked(True)
        self.RLSR_BIAS_Ch.setObjectName("RLSR_BIAS_Ch")
        self.LSR_PDI_Ch = QtWidgets.QCheckBox(Dialog)
        self.LSR_PDI_Ch.setGeometry(QtCore.QRect(890, 260, 21, 17))
        self.LSR_PDI_Ch.setText("")
        self.LSR_PDI_Ch.setChecked(True)
        self.LSR_PDI_Ch.setObjectName("LSR_PDI_Ch")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(880, 10, 41, 31))
        self.label_2.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 85, 41);")
        self.label_2.setObjectName("label_2")
        self.groupBoxDc = QtWidgets.QGroupBox(Dialog)
        self.groupBoxDc.setGeometry(QtCore.QRect(10, 10, 401, 341))
        self.groupBoxDc.setStyleSheet("border-color: rgb(0, 168, 81);")
        self.groupBoxDc.setObjectName("groupBoxDc")
        self.label_9 = QtWidgets.QLabel(self.groupBoxDc)
        self.label_9.setGeometry(QtCore.QRect(20, 250, 111, 21))
        self.label_9.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_9.setObjectName("label_9")
        self.label_7 = QtWidgets.QLabel(self.groupBoxDc)
        self.label_7.setGeometry(QtCore.QRect(20, 160, 111, 21))
        self.label_7.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setObjectName("label_7")
        self.label_v5 = QtWidgets.QLabel(self.groupBoxDc)
        self.label_v5.setGeometry(QtCore.QRect(20, 280, 111, 21))
        self.label_v5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_v5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_v5.setObjectName("label_v5")
        self.label_4 = QtWidgets.QLabel(self.groupBoxDc)
        self.label_4.setGeometry(QtCore.QRect(20, 40, 111, 21))
        self.label_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.groupBoxDc)
        self.label.setGeometry(QtCore.QRect(150, 10, 221, 31))
        self.label.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 85, 41);")
        self.label.setObjectName("label")
        self.label_10 = QtWidgets.QLabel(self.groupBoxDc)
        self.label_10.setGeometry(QtCore.QRect(20, 220, 111, 21))
        self.label_10.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_10.setObjectName("label_10")
        self.label_5 = QtWidgets.QLabel(self.groupBoxDc)
        self.label_5.setGeometry(QtCore.QRect(20, 100, 111, 21))
        self.label_5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setObjectName("label_5")
        self.label_11 = QtWidgets.QLabel(self.groupBoxDc)
        self.label_11.setGeometry(QtCore.QRect(20, 190, 111, 21))
        self.label_11.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_11.setObjectName("label_11")
        self.label_6 = QtWidgets.QLabel(self.groupBoxDc)
        self.label_6.setGeometry(QtCore.QRect(20, 130, 111, 21))
        self.label_6.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(self.groupBoxDc)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 111, 21))
        self.label_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setObjectName("label_3")
        self.label_VIN = QtWidgets.QLabel(self.groupBoxDc)
        self.label_VIN.setGeometry(QtCore.QRect(20, 310, 111, 21))
        self.label_VIN.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_VIN.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_VIN.setObjectName("label_VIN")
        self.ModuleTemp_LA = QtWidgets.QLabel(self.groupBoxDc)
        self.ModuleTemp_LA.setGeometry(QtCore.QRect(140, 40, 41, 20))
        self.ModuleTemp_LA.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.ModuleTemp_LA.setFrameShape(QtWidgets.QFrame.Box)
        self.ModuleTemp_LA.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ModuleTemp_LA.setText("")
        self.ModuleTemp_LA.setAlignment(QtCore.Qt.AlignCenter)
        self.ModuleTemp_LA.setObjectName("ModuleTemp_LA")
        self.ModuleTemp_OK = QtWidgets.QLabel(self.groupBoxDc)
        self.ModuleTemp_OK.setGeometry(QtCore.QRect(240, 40, 41, 20))
        self.ModuleTemp_OK.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.ModuleTemp_OK.setFrameShape(QtWidgets.QFrame.Box)
        self.ModuleTemp_OK.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ModuleTemp_OK.setText("")
        self.ModuleTemp_OK.setAlignment(QtCore.Qt.AlignCenter)
        self.ModuleTemp_OK.setObjectName("ModuleTemp_OK")
        self.ModuleTemp_HA = QtWidgets.QLabel(self.groupBoxDc)
        self.ModuleTemp_HA.setGeometry(QtCore.QRect(340, 40, 41, 20))
        self.ModuleTemp_HA.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.ModuleTemp_HA.setFrameShape(QtWidgets.QFrame.Box)
        self.ModuleTemp_HA.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ModuleTemp_HA.setText("")
        self.ModuleTemp_HA.setAlignment(QtCore.Qt.AlignCenter)
        self.ModuleTemp_HA.setObjectName("ModuleTemp_HA")
        self.TEC_I_MON_HA = QtWidgets.QLabel(self.groupBoxDc)
        self.TEC_I_MON_HA.setGeometry(QtCore.QRect(340, 70, 41, 20))
        self.TEC_I_MON_HA.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.TEC_I_MON_HA.setFrameShape(QtWidgets.QFrame.Box)
        self.TEC_I_MON_HA.setFrameShadow(QtWidgets.QFrame.Plain)
        self.TEC_I_MON_HA.setText("")
        self.TEC_I_MON_HA.setAlignment(QtCore.Qt.AlignCenter)
        self.TEC_I_MON_HA.setObjectName("TEC_I_MON_HA")
        self.TEC_I_MON_OK = QtWidgets.QLabel(self.groupBoxDc)
        self.TEC_I_MON_OK.setGeometry(QtCore.QRect(240, 70, 41, 20))
        self.TEC_I_MON_OK.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.TEC_I_MON_OK.setFrameShape(QtWidgets.QFrame.Box)
        self.TEC_I_MON_OK.setFrameShadow(QtWidgets.QFrame.Plain)
        self.TEC_I_MON_OK.setText("")
        self.TEC_I_MON_OK.setAlignment(QtCore.Qt.AlignCenter)
        self.TEC_I_MON_OK.setObjectName("TEC_I_MON_OK")
        self.TEC_I_MON_LA = QtWidgets.QLabel(self.groupBoxDc)
        self.TEC_I_MON_LA.setGeometry(QtCore.QRect(140, 70, 41, 20))
        self.TEC_I_MON_LA.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.TEC_I_MON_LA.setFrameShape(QtWidgets.QFrame.Box)
        self.TEC_I_MON_LA.setFrameShadow(QtWidgets.QFrame.Plain)
        self.TEC_I_MON_LA.setText("")
        self.TEC_I_MON_LA.setAlignment(QtCore.Qt.AlignCenter)
        self.TEC_I_MON_LA.setObjectName("TEC_I_MON_LA")
        self.Laser_Temp_HA = QtWidgets.QLabel(self.groupBoxDc)
        self.Laser_Temp_HA.setGeometry(QtCore.QRect(340, 100, 41, 20))
        self.Laser_Temp_HA.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.Laser_Temp_HA.setFrameShape(QtWidgets.QFrame.Box)
        self.Laser_Temp_HA.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Laser_Temp_HA.setText("")
        self.Laser_Temp_HA.setAlignment(QtCore.Qt.AlignCenter)
        self.Laser_Temp_HA.setObjectName("Laser_Temp_HA")
        self.Laser_Temp_OK = QtWidgets.QLabel(self.groupBoxDc)
        self.Laser_Temp_OK.setGeometry(QtCore.QRect(240, 100, 41, 20))
        self.Laser_Temp_OK.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.Laser_Temp_OK.setFrameShape(QtWidgets.QFrame.Box)
        self.Laser_Temp_OK.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Laser_Temp_OK.setText("")
        self.Laser_Temp_OK.setAlignment(QtCore.Qt.AlignCenter)
        self.Laser_Temp_OK.setObjectName("Laser_Temp_OK")
        self.Laser_Temp_LA = QtWidgets.QLabel(self.groupBoxDc)
        self.Laser_Temp_LA.setGeometry(QtCore.QRect(140, 100, 41, 20))
        self.Laser_Temp_LA.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.Laser_Temp_LA.setFrameShape(QtWidgets.QFrame.Box)
        self.Laser_Temp_LA.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Laser_Temp_LA.setText("")
        self.Laser_Temp_LA.setAlignment(QtCore.Qt.AlignCenter)
        self.Laser_Temp_LA.setObjectName("Laser_Temp_LA")
        self.Laser_Temp_LW = QtWidgets.QLabel(self.groupBoxDc)
        self.Laser_Temp_LW.setGeometry(QtCore.QRect(190, 100, 41, 20))
        self.Laser_Temp_LW.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.Laser_Temp_LW.setFrameShape(QtWidgets.QFrame.Box)
        self.Laser_Temp_LW.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Laser_Temp_LW.setText("")
        self.Laser_Temp_LW.setAlignment(QtCore.Qt.AlignCenter)
        self.Laser_Temp_LW.setObjectName("Laser_Temp_LW")
        self.Laser_Temp_HW = QtWidgets.QLabel(self.groupBoxDc)
        self.Laser_Temp_HW.setGeometry(QtCore.QRect(290, 100, 41, 20))
        self.Laser_Temp_HW.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.Laser_Temp_HW.setFrameShape(QtWidgets.QFrame.Box)
        self.Laser_Temp_HW.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Laser_Temp_HW.setText("")
        self.Laser_Temp_HW.setAlignment(QtCore.Qt.AlignCenter)
        self.Laser_Temp_HW.setObjectName("Laser_Temp_HW")
        self.LAS_RF_HA = QtWidgets.QLabel(self.groupBoxDc)
        self.LAS_RF_HA.setGeometry(QtCore.QRect(340, 160, 41, 20))
        self.LAS_RF_HA.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.LAS_RF_HA.setFrameShape(QtWidgets.QFrame.Box)
        self.LAS_RF_HA.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LAS_RF_HA.setText("")
        self.LAS_RF_HA.setAlignment(QtCore.Qt.AlignCenter)
        self.LAS_RF_HA.setObjectName("LAS_RF_HA")
        self.LAS_RF_OK = QtWidgets.QLabel(self.groupBoxDc)
        self.LAS_RF_OK.setGeometry(QtCore.QRect(240, 160, 41, 20))
        self.LAS_RF_OK.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.LAS_RF_OK.setFrameShape(QtWidgets.QFrame.Box)
        self.LAS_RF_OK.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LAS_RF_OK.setText("")
        self.LAS_RF_OK.setAlignment(QtCore.Qt.AlignCenter)
        self.LAS_RF_OK.setObjectName("LAS_RF_OK")
        self.Input_RF_MON_OK = QtWidgets.QLabel(self.groupBoxDc)
        self.Input_RF_MON_OK.setGeometry(QtCore.QRect(240, 130, 41, 20))
        self.Input_RF_MON_OK.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.Input_RF_MON_OK.setFrameShape(QtWidgets.QFrame.Box)
        self.Input_RF_MON_OK.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Input_RF_MON_OK.setText("")
        self.Input_RF_MON_OK.setAlignment(QtCore.Qt.AlignCenter)
        self.Input_RF_MON_OK.setObjectName("Input_RF_MON_OK")
        self.Input_RF_MON_LA = QtWidgets.QLabel(self.groupBoxDc)
        self.Input_RF_MON_LA.setGeometry(QtCore.QRect(140, 130, 41, 20))
        self.Input_RF_MON_LA.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.Input_RF_MON_LA.setFrameShape(QtWidgets.QFrame.Box)
        self.Input_RF_MON_LA.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Input_RF_MON_LA.setText("")
        self.Input_RF_MON_LA.setAlignment(QtCore.Qt.AlignCenter)
        self.Input_RF_MON_LA.setObjectName("Input_RF_MON_LA")
        self.LAS_RF_LA = QtWidgets.QLabel(self.groupBoxDc)
        self.LAS_RF_LA.setGeometry(QtCore.QRect(140, 160, 41, 20))
        self.LAS_RF_LA.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.LAS_RF_LA.setFrameShape(QtWidgets.QFrame.Box)
        self.LAS_RF_LA.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LAS_RF_LA.setText("")
        self.LAS_RF_LA.setAlignment(QtCore.Qt.AlignCenter)
        self.LAS_RF_LA.setObjectName("LAS_RF_LA")
        self.Input_RF_MON_HA = QtWidgets.QLabel(self.groupBoxDc)
        self.Input_RF_MON_HA.setGeometry(QtCore.QRect(340, 130, 41, 20))
        self.Input_RF_MON_HA.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.Input_RF_MON_HA.setFrameShape(QtWidgets.QFrame.Box)
        self.Input_RF_MON_HA.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Input_RF_MON_HA.setText("")
        self.Input_RF_MON_HA.setAlignment(QtCore.Qt.AlignCenter)
        self.Input_RF_MON_HA.setObjectName("Input_RF_MON_HA")
        self.FLSR_BIAS_HA = QtWidgets.QLabel(self.groupBoxDc)
        self.FLSR_BIAS_HA.setGeometry(QtCore.QRect(340, 190, 41, 20))
        self.FLSR_BIAS_HA.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.FLSR_BIAS_HA.setFrameShape(QtWidgets.QFrame.Box)
        self.FLSR_BIAS_HA.setFrameShadow(QtWidgets.QFrame.Plain)
        self.FLSR_BIAS_HA.setText("")
        self.FLSR_BIAS_HA.setAlignment(QtCore.Qt.AlignCenter)
        self.FLSR_BIAS_HA.setObjectName("FLSR_BIAS_HA")
        self.FLSR_BIAS_LA = QtWidgets.QLabel(self.groupBoxDc)
        self.FLSR_BIAS_LA.setGeometry(QtCore.QRect(140, 190, 41, 20))
        self.FLSR_BIAS_LA.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.FLSR_BIAS_LA.setFrameShape(QtWidgets.QFrame.Box)
        self.FLSR_BIAS_LA.setFrameShadow(QtWidgets.QFrame.Plain)
        self.FLSR_BIAS_LA.setText("")
        self.FLSR_BIAS_LA.setAlignment(QtCore.Qt.AlignCenter)
        self.FLSR_BIAS_LA.setObjectName("FLSR_BIAS_LA")
        self.FLSR_BIAS_OK = QtWidgets.QLabel(self.groupBoxDc)
        self.FLSR_BIAS_OK.setGeometry(QtCore.QRect(240, 190, 41, 20))
        self.FLSR_BIAS_OK.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.FLSR_BIAS_OK.setFrameShape(QtWidgets.QFrame.Box)
        self.FLSR_BIAS_OK.setFrameShadow(QtWidgets.QFrame.Plain)
        self.FLSR_BIAS_OK.setText("")
        self.FLSR_BIAS_OK.setAlignment(QtCore.Qt.AlignCenter)
        self.FLSR_BIAS_OK.setObjectName("FLSR_BIAS_OK")
        self.FLSR_BIAS_LW = QtWidgets.QLabel(self.groupBoxDc)
        self.FLSR_BIAS_LW.setGeometry(QtCore.QRect(190, 190, 41, 20))
        self.FLSR_BIAS_LW.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.FLSR_BIAS_LW.setFrameShape(QtWidgets.QFrame.Box)
        self.FLSR_BIAS_LW.setFrameShadow(QtWidgets.QFrame.Plain)
        self.FLSR_BIAS_LW.setText("")
        self.FLSR_BIAS_LW.setAlignment(QtCore.Qt.AlignCenter)
        self.FLSR_BIAS_LW.setObjectName("FLSR_BIAS_LW")
        self.FLSR_BIAS_HW = QtWidgets.QLabel(self.groupBoxDc)
        self.FLSR_BIAS_HW.setGeometry(QtCore.QRect(290, 190, 41, 20))
        self.FLSR_BIAS_HW.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.FLSR_BIAS_HW.setFrameShape(QtWidgets.QFrame.Box)
        self.FLSR_BIAS_HW.setFrameShadow(QtWidgets.QFrame.Plain)
        self.FLSR_BIAS_HW.setText("")
        self.FLSR_BIAS_HW.setAlignment(QtCore.Qt.AlignCenter)
        self.FLSR_BIAS_HW.setObjectName("FLSR_BIAS_HW")
        self.RLSR_BIAS_LA = QtWidgets.QLabel(self.groupBoxDc)
        self.RLSR_BIAS_LA.setGeometry(QtCore.QRect(140, 220, 41, 20))
        self.RLSR_BIAS_LA.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.RLSR_BIAS_LA.setFrameShape(QtWidgets.QFrame.Box)
        self.RLSR_BIAS_LA.setFrameShadow(QtWidgets.QFrame.Plain)
        self.RLSR_BIAS_LA.setText("")
        self.RLSR_BIAS_LA.setAlignment(QtCore.Qt.AlignCenter)
        self.RLSR_BIAS_LA.setObjectName("RLSR_BIAS_LA")
        self.RLSR_BIAS_OK = QtWidgets.QLabel(self.groupBoxDc)
        self.RLSR_BIAS_OK.setGeometry(QtCore.QRect(240, 220, 41, 20))
        self.RLSR_BIAS_OK.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.RLSR_BIAS_OK.setFrameShape(QtWidgets.QFrame.Box)
        self.RLSR_BIAS_OK.setFrameShadow(QtWidgets.QFrame.Plain)
        self.RLSR_BIAS_OK.setText("")
        self.RLSR_BIAS_OK.setAlignment(QtCore.Qt.AlignCenter)
        self.RLSR_BIAS_OK.setObjectName("RLSR_BIAS_OK")
        self.RLSR_BIAS_HA = QtWidgets.QLabel(self.groupBoxDc)
        self.RLSR_BIAS_HA.setGeometry(QtCore.QRect(340, 220, 41, 20))
        self.RLSR_BIAS_HA.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.RLSR_BIAS_HA.setFrameShape(QtWidgets.QFrame.Box)
        self.RLSR_BIAS_HA.setFrameShadow(QtWidgets.QFrame.Plain)
        self.RLSR_BIAS_HA.setText("")
        self.RLSR_BIAS_HA.setAlignment(QtCore.Qt.AlignCenter)
        self.RLSR_BIAS_HA.setObjectName("RLSR_BIAS_HA")
        self.RLSR_BIAS_LW = QtWidgets.QLabel(self.groupBoxDc)
        self.RLSR_BIAS_LW.setGeometry(QtCore.QRect(190, 220, 41, 20))
        self.RLSR_BIAS_LW.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.RLSR_BIAS_LW.setFrameShape(QtWidgets.QFrame.Box)
        self.RLSR_BIAS_LW.setFrameShadow(QtWidgets.QFrame.Plain)
        self.RLSR_BIAS_LW.setText("")
        self.RLSR_BIAS_LW.setAlignment(QtCore.Qt.AlignCenter)
        self.RLSR_BIAS_LW.setObjectName("RLSR_BIAS_LW")
        self.RLSR_BIAS_HW = QtWidgets.QLabel(self.groupBoxDc)
        self.RLSR_BIAS_HW.setGeometry(QtCore.QRect(290, 220, 41, 20))
        self.RLSR_BIAS_HW.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.RLSR_BIAS_HW.setFrameShape(QtWidgets.QFrame.Box)
        self.RLSR_BIAS_HW.setFrameShadow(QtWidgets.QFrame.Plain)
        self.RLSR_BIAS_HW.setText("")
        self.RLSR_BIAS_HW.setAlignment(QtCore.Qt.AlignCenter)
        self.RLSR_BIAS_HW.setObjectName("RLSR_BIAS_HW")
        self.LSR_PDI_OK = QtWidgets.QLabel(self.groupBoxDc)
        self.LSR_PDI_OK.setGeometry(QtCore.QRect(240, 250, 41, 20))
        self.LSR_PDI_OK.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.LSR_PDI_OK.setFrameShape(QtWidgets.QFrame.Box)
        self.LSR_PDI_OK.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LSR_PDI_OK.setText("")
        self.LSR_PDI_OK.setAlignment(QtCore.Qt.AlignCenter)
        self.LSR_PDI_OK.setObjectName("LSR_PDI_OK")
        self.v5_LA = QtWidgets.QLabel(self.groupBoxDc)
        self.v5_LA.setGeometry(QtCore.QRect(140, 280, 41, 20))
        self.v5_LA.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.v5_LA.setFrameShape(QtWidgets.QFrame.Box)
        self.v5_LA.setFrameShadow(QtWidgets.QFrame.Plain)
        self.v5_LA.setText("")
        self.v5_LA.setAlignment(QtCore.Qt.AlignCenter)
        self.v5_LA.setObjectName("v5_LA")
        self.v5_OK = QtWidgets.QLabel(self.groupBoxDc)
        self.v5_OK.setGeometry(QtCore.QRect(240, 280, 41, 20))
        self.v5_OK.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.v5_OK.setFrameShape(QtWidgets.QFrame.Box)
        self.v5_OK.setFrameShadow(QtWidgets.QFrame.Plain)
        self.v5_OK.setText("")
        self.v5_OK.setAlignment(QtCore.Qt.AlignCenter)
        self.v5_OK.setObjectName("v5_OK")
        self.LSR_PDI_HA = QtWidgets.QLabel(self.groupBoxDc)
        self.LSR_PDI_HA.setGeometry(QtCore.QRect(340, 250, 41, 20))
        self.LSR_PDI_HA.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.LSR_PDI_HA.setFrameShape(QtWidgets.QFrame.Box)
        self.LSR_PDI_HA.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LSR_PDI_HA.setText("")
        self.LSR_PDI_HA.setAlignment(QtCore.Qt.AlignCenter)
        self.LSR_PDI_HA.setObjectName("LSR_PDI_HA")
        self.LSR_PDI_LW = QtWidgets.QLabel(self.groupBoxDc)
        self.LSR_PDI_LW.setGeometry(QtCore.QRect(190, 250, 41, 20))
        self.LSR_PDI_LW.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.LSR_PDI_LW.setFrameShape(QtWidgets.QFrame.Box)
        self.LSR_PDI_LW.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LSR_PDI_LW.setText("")
        self.LSR_PDI_LW.setAlignment(QtCore.Qt.AlignCenter)
        self.LSR_PDI_LW.setObjectName("LSR_PDI_LW")
        self.v5_HW = QtWidgets.QLabel(self.groupBoxDc)
        self.v5_HW.setGeometry(QtCore.QRect(290, 280, 41, 20))
        self.v5_HW.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.v5_HW.setFrameShape(QtWidgets.QFrame.Box)
        self.v5_HW.setFrameShadow(QtWidgets.QFrame.Plain)
        self.v5_HW.setText("")
        self.v5_HW.setAlignment(QtCore.Qt.AlignCenter)
        self.v5_HW.setObjectName("v5_HW")
        self.v5_HA = QtWidgets.QLabel(self.groupBoxDc)
        self.v5_HA.setGeometry(QtCore.QRect(340, 280, 41, 20))
        self.v5_HA.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.v5_HA.setFrameShape(QtWidgets.QFrame.Box)
        self.v5_HA.setFrameShadow(QtWidgets.QFrame.Plain)
        self.v5_HA.setText("")
        self.v5_HA.setAlignment(QtCore.Qt.AlignCenter)
        self.v5_HA.setObjectName("v5_HA")
        self.LSR_PDI_LA = QtWidgets.QLabel(self.groupBoxDc)
        self.LSR_PDI_LA.setGeometry(QtCore.QRect(140, 250, 41, 20))
        self.LSR_PDI_LA.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.LSR_PDI_LA.setFrameShape(QtWidgets.QFrame.Box)
        self.LSR_PDI_LA.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LSR_PDI_LA.setText("")
        self.LSR_PDI_LA.setAlignment(QtCore.Qt.AlignCenter)
        self.LSR_PDI_LA.setObjectName("LSR_PDI_LA")
        self.LSR_PDI_HW = QtWidgets.QLabel(self.groupBoxDc)
        self.LSR_PDI_HW.setGeometry(QtCore.QRect(290, 250, 41, 20))
        self.LSR_PDI_HW.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.LSR_PDI_HW.setFrameShape(QtWidgets.QFrame.Box)
        self.LSR_PDI_HW.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LSR_PDI_HW.setText("")
        self.LSR_PDI_HW.setAlignment(QtCore.Qt.AlignCenter)
        self.LSR_PDI_HW.setObjectName("LSR_PDI_HW")
        self.v5_LW = QtWidgets.QLabel(self.groupBoxDc)
        self.v5_LW.setGeometry(QtCore.QRect(190, 280, 41, 20))
        self.v5_LW.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.v5_LW.setFrameShape(QtWidgets.QFrame.Box)
        self.v5_LW.setFrameShadow(QtWidgets.QFrame.Plain)
        self.v5_LW.setText("")
        self.v5_LW.setAlignment(QtCore.Qt.AlignCenter)
        self.v5_LW.setObjectName("v5_LW")
        self.v24_LA = QtWidgets.QLabel(self.groupBoxDc)
        self.v24_LA.setGeometry(QtCore.QRect(140, 310, 41, 20))
        self.v24_LA.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.v24_LA.setFrameShape(QtWidgets.QFrame.Box)
        self.v24_LA.setFrameShadow(QtWidgets.QFrame.Plain)
        self.v24_LA.setText("")
        self.v24_LA.setAlignment(QtCore.Qt.AlignCenter)
        self.v24_LA.setObjectName("v24_LA")
        self.v24_OK = QtWidgets.QLabel(self.groupBoxDc)
        self.v24_OK.setGeometry(QtCore.QRect(240, 310, 41, 20))
        self.v24_OK.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.v24_OK.setFrameShape(QtWidgets.QFrame.Box)
        self.v24_OK.setFrameShadow(QtWidgets.QFrame.Plain)
        self.v24_OK.setText("")
        self.v24_OK.setAlignment(QtCore.Qt.AlignCenter)
        self.v24_OK.setObjectName("v24_OK")
        self.v24_HW = QtWidgets.QLabel(self.groupBoxDc)
        self.v24_HW.setGeometry(QtCore.QRect(290, 310, 41, 20))
        self.v24_HW.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.v24_HW.setFrameShape(QtWidgets.QFrame.Box)
        self.v24_HW.setFrameShadow(QtWidgets.QFrame.Plain)
        self.v24_HW.setText("")
        self.v24_HW.setAlignment(QtCore.Qt.AlignCenter)
        self.v24_HW.setObjectName("v24_HW")
        self.v24_LW = QtWidgets.QLabel(self.groupBoxDc)
        self.v24_LW.setGeometry(QtCore.QRect(190, 310, 41, 20))
        self.v24_LW.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.v24_LW.setFrameShape(QtWidgets.QFrame.Box)
        self.v24_LW.setFrameShadow(QtWidgets.QFrame.Plain)
        self.v24_LW.setText("")
        self.v24_LW.setAlignment(QtCore.Qt.AlignCenter)
        self.v24_LW.setObjectName("v24_LW")
        self.v24_HA = QtWidgets.QLabel(self.groupBoxDc)
        self.v24_HA.setGeometry(QtCore.QRect(340, 310, 41, 20))
        self.v24_HA.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.v24_HA.setFrameShape(QtWidgets.QFrame.Box)
        self.v24_HA.setFrameShadow(QtWidgets.QFrame.Plain)
        self.v24_HA.setText("")
        self.v24_HA.setAlignment(QtCore.Qt.AlignCenter)
        self.v24_HA.setObjectName("v24_HA")
        self.groupBox_Un = QtWidgets.QGroupBox(Dialog)
        self.groupBox_Un.setGeometry(QtCore.QRect(420, 10, 441, 341))
        self.groupBox_Un.setStyleSheet("border-color: rgb(0, 168, 81);")
        self.groupBox_Un.setObjectName("groupBox_Un")
        self.label_16 = QtWidgets.QLabel(self.groupBox_Un)
        self.label_16.setGeometry(QtCore.QRect(10, 40, 111, 21))
        self.label_16.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_16.setObjectName("label_16")
        self.label_19 = QtWidgets.QLabel(self.groupBox_Un)
        self.label_19.setGeometry(QtCore.QRect(10, 220, 111, 21))
        self.label_19.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_Un)
        self.label_20.setGeometry(QtCore.QRect(10, 100, 111, 21))
        self.label_20.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_Un)
        self.label_21.setGeometry(QtCore.QRect(10, 190, 111, 21))
        self.label_21.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_21.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_21.setObjectName("label_21")
        self.label_23 = QtWidgets.QLabel(self.groupBox_Un)
        self.label_23.setGeometry(QtCore.QRect(10, 70, 111, 21))
        self.label_23.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_23.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_23.setObjectName("label_23")
        self.label_13 = QtWidgets.QLabel(self.groupBox_Un)
        self.label_13.setGeometry(QtCore.QRect(10, 130, 119, 21))
        self.label_13.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_Un)
        self.label_14.setGeometry(QtCore.QRect(10, 160, 111, 21))
        self.label_14.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_14.setObjectName("label_14")
        self.label_17 = QtWidgets.QLabel(self.groupBox_Un)
        self.label_17.setGeometry(QtCore.QRect(10, 250, 111, 21))
        self.label_17.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_17.setObjectName("label_17")
        self.LAS_RF_OK_2 = QtWidgets.QLabel(self.groupBox_Un)
        self.LAS_RF_OK_2.setGeometry(QtCore.QRect(260, 160, 51, 20))
        self.LAS_RF_OK_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.LAS_RF_OK_2.setFrameShape(QtWidgets.QFrame.Box)
        self.LAS_RF_OK_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LAS_RF_OK_2.setText("")
        self.LAS_RF_OK_2.setAlignment(QtCore.Qt.AlignCenter)
        self.LAS_RF_OK_2.setObjectName("LAS_RF_OK_2")
        self.TEC_I_MON_OK_2 = QtWidgets.QLabel(self.groupBox_Un)
        self.TEC_I_MON_OK_2.setGeometry(QtCore.QRect(260, 70, 51, 20))
        self.TEC_I_MON_OK_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.TEC_I_MON_OK_2.setFrameShape(QtWidgets.QFrame.Box)
        self.TEC_I_MON_OK_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.TEC_I_MON_OK_2.setText("")
        self.TEC_I_MON_OK_2.setAlignment(QtCore.Qt.AlignCenter)
        self.TEC_I_MON_OK_2.setObjectName("TEC_I_MON_OK_2")
        self.LSR_PDI_OK_2 = QtWidgets.QLabel(self.groupBox_Un)
        self.LSR_PDI_OK_2.setGeometry(QtCore.QRect(260, 250, 51, 20))
        self.LSR_PDI_OK_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.LSR_PDI_OK_2.setFrameShape(QtWidgets.QFrame.Box)
        self.LSR_PDI_OK_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LSR_PDI_OK_2.setText("")
        self.LSR_PDI_OK_2.setAlignment(QtCore.Qt.AlignCenter)
        self.LSR_PDI_OK_2.setObjectName("LSR_PDI_OK_2")
        self.ModuleTemp_OK_2 = QtWidgets.QLabel(self.groupBox_Un)
        self.ModuleTemp_OK_2.setGeometry(QtCore.QRect(260, 40, 51, 20))
        self.ModuleTemp_OK_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.ModuleTemp_OK_2.setFrameShape(QtWidgets.QFrame.Box)
        self.ModuleTemp_OK_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ModuleTemp_OK_2.setText("")
        self.ModuleTemp_OK_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ModuleTemp_OK_2.setObjectName("ModuleTemp_OK_2")
        self.FLSR_BIAS_OK_2 = QtWidgets.QLabel(self.groupBox_Un)
        self.FLSR_BIAS_OK_2.setGeometry(QtCore.QRect(260, 190, 51, 20))
        self.FLSR_BIAS_OK_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.FLSR_BIAS_OK_2.setFrameShape(QtWidgets.QFrame.Box)
        self.FLSR_BIAS_OK_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.FLSR_BIAS_OK_2.setText("")
        self.FLSR_BIAS_OK_2.setAlignment(QtCore.Qt.AlignCenter)
        self.FLSR_BIAS_OK_2.setObjectName("FLSR_BIAS_OK_2")
        self.RLSR_BIAS_OK_2 = QtWidgets.QLabel(self.groupBox_Un)
        self.RLSR_BIAS_OK_2.setGeometry(QtCore.QRect(260, 220, 51, 20))
        self.RLSR_BIAS_OK_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.RLSR_BIAS_OK_2.setFrameShape(QtWidgets.QFrame.Box)
        self.RLSR_BIAS_OK_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.RLSR_BIAS_OK_2.setText("")
        self.RLSR_BIAS_OK_2.setAlignment(QtCore.Qt.AlignCenter)
        self.RLSR_BIAS_OK_2.setObjectName("RLSR_BIAS_OK_2")
        self.Laser_Temp_OK_2 = QtWidgets.QLabel(self.groupBox_Un)
        self.Laser_Temp_OK_2.setGeometry(QtCore.QRect(260, 100, 51, 20))
        self.Laser_Temp_OK_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.Laser_Temp_OK_2.setFrameShape(QtWidgets.QFrame.Box)
        self.Laser_Temp_OK_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Laser_Temp_OK_2.setText("")
        self.Laser_Temp_OK_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Laser_Temp_OK_2.setObjectName("Laser_Temp_OK_2")
        self.Input_RF_MON_OK_2 = QtWidgets.QLabel(self.groupBox_Un)
        self.Input_RF_MON_OK_2.setGeometry(QtCore.QRect(260, 130, 51, 20))
        self.Input_RF_MON_OK_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.Input_RF_MON_OK_2.setFrameShape(QtWidgets.QFrame.Box)
        self.Input_RF_MON_OK_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Input_RF_MON_OK_2.setText("")
        self.Input_RF_MON_OK_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Input_RF_MON_OK_2.setObjectName("Input_RF_MON_OK_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_Un)
        self.label_8.setGeometry(QtCore.QRect(160, 10, 271, 31))
        self.label_8.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 85, 41);")
        self.label_8.setObjectName("label_8")
        self.ModuleTemp_LA_2 = QtWidgets.QLineEdit(self.groupBox_Un)
        self.ModuleTemp_LA_2.setGeometry(QtCore.QRect(140, 40, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ModuleTemp_LA_2.setFont(font)
        self.ModuleTemp_LA_2.setObjectName("ModuleTemp_LA_2")
        self.FLSR_BIAS_LA_2 = QtWidgets.QLineEdit(self.groupBox_Un)
        self.FLSR_BIAS_LA_2.setGeometry(QtCore.QRect(140, 190, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.FLSR_BIAS_LA_2.setFont(font)
        self.FLSR_BIAS_LA_2.setObjectName("FLSR_BIAS_LA_2")
        self.LSR_PDI_LA_2 = QtWidgets.QLineEdit(self.groupBox_Un)
        self.LSR_PDI_LA_2.setGeometry(QtCore.QRect(140, 250, 51, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.LSR_PDI_LA_2.setFont(font)
        self.LSR_PDI_LA_2.setStyleSheet("")
        self.LSR_PDI_LA_2.setObjectName("LSR_PDI_LA_2")
        self.Laser_Temp_LA_2 = QtWidgets.QLineEdit(self.groupBox_Un)
        self.Laser_Temp_LA_2.setGeometry(QtCore.QRect(140, 100, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Laser_Temp_LA_2.setFont(font)
        self.Laser_Temp_LA_2.setObjectName("Laser_Temp_LA_2")
        self.RLSR_BIAS_LA_2 = QtWidgets.QLineEdit(self.groupBox_Un)
        self.RLSR_BIAS_LA_2.setGeometry(QtCore.QRect(140, 220, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.RLSR_BIAS_LA_2.setFont(font)
        self.RLSR_BIAS_LA_2.setObjectName("RLSR_BIAS_LA_2")
        self.Input_RF_MON_LA_2 = QtWidgets.QLineEdit(self.groupBox_Un)
        self.Input_RF_MON_LA_2.setGeometry(QtCore.QRect(140, 130, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Input_RF_MON_LA_2.setFont(font)
        self.Input_RF_MON_LA_2.setObjectName("Input_RF_MON_LA_2")
        self.LAS_RF_LA_2 = QtWidgets.QLineEdit(self.groupBox_Un)
        self.LAS_RF_LA_2.setGeometry(QtCore.QRect(140, 160, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LAS_RF_LA_2.setFont(font)
        self.LAS_RF_LA_2.setObjectName("LAS_RF_LA_2")
        self.TEC_I_MON_LA_2 = QtWidgets.QLineEdit(self.groupBox_Un)
        self.TEC_I_MON_LA_2.setGeometry(QtCore.QRect(140, 70, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TEC_I_MON_LA_2.setFont(font)
        self.TEC_I_MON_LA_2.setObjectName("TEC_I_MON_LA_2")
        self.Laser_Temp_LW_2 = QtWidgets.QLineEdit(self.groupBox_Un)
        self.Laser_Temp_LW_2.setGeometry(QtCore.QRect(200, 100, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Laser_Temp_LW_2.setFont(font)
        self.Laser_Temp_LW_2.setObjectName("Laser_Temp_LW_2")
        self.RLSR_BIAS_LW_2 = QtWidgets.QLineEdit(self.groupBox_Un)
        self.RLSR_BIAS_LW_2.setGeometry(QtCore.QRect(200, 220, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.RLSR_BIAS_LW_2.setFont(font)
        self.RLSR_BIAS_LW_2.setObjectName("RLSR_BIAS_LW_2")
        self.LSR_PDI_LW_2 = QtWidgets.QLineEdit(self.groupBox_Un)
        self.LSR_PDI_LW_2.setGeometry(QtCore.QRect(200, 250, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LSR_PDI_LW_2.setFont(font)
        self.LSR_PDI_LW_2.setObjectName("LSR_PDI_LW_2")
        self.FLSR_BIAS_LW_2 = QtWidgets.QLineEdit(self.groupBox_Un)
        self.FLSR_BIAS_LW_2.setGeometry(QtCore.QRect(200, 190, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.FLSR_BIAS_LW_2.setFont(font)
        self.FLSR_BIAS_LW_2.setObjectName("FLSR_BIAS_LW_2")
        self.Laser_Temp_HW_2 = QtWidgets.QLineEdit(self.groupBox_Un)
        self.Laser_Temp_HW_2.setGeometry(QtCore.QRect(320, 100, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Laser_Temp_HW_2.setFont(font)
        self.Laser_Temp_HW_2.setObjectName("Laser_Temp_HW_2")
        self.RLSR_BIAS_HW_2 = QtWidgets.QLineEdit(self.groupBox_Un)
        self.RLSR_BIAS_HW_2.setGeometry(QtCore.QRect(320, 220, 51, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.RLSR_BIAS_HW_2.setFont(font)
        self.RLSR_BIAS_HW_2.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.RLSR_BIAS_HW_2.setObjectName("RLSR_BIAS_HW_2")
        self.FLSR_BIAS_HW_2 = QtWidgets.QLineEdit(self.groupBox_Un)
        self.FLSR_BIAS_HW_2.setGeometry(QtCore.QRect(320, 190, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.FLSR_BIAS_HW_2.setFont(font)
        self.FLSR_BIAS_HW_2.setObjectName("FLSR_BIAS_HW_2")
        self.LSR_PDI_HW_2 = QtWidgets.QLineEdit(self.groupBox_Un)
        self.LSR_PDI_HW_2.setGeometry(QtCore.QRect(320, 250, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LSR_PDI_HW_2.setFont(font)
        self.LSR_PDI_HW_2.setObjectName("LSR_PDI_HW_2")
        self.TEC_I_MON_HA_2 = QtWidgets.QLineEdit(self.groupBox_Un)
        self.TEC_I_MON_HA_2.setGeometry(QtCore.QRect(380, 70, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TEC_I_MON_HA_2.setFont(font)
        self.TEC_I_MON_HA_2.setObjectName("TEC_I_MON_HA_2")
        self.Laser_Temp_HA_2 = QtWidgets.QLineEdit(self.groupBox_Un)
        self.Laser_Temp_HA_2.setGeometry(QtCore.QRect(380, 100, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Laser_Temp_HA_2.setFont(font)
        self.Laser_Temp_HA_2.setObjectName("Laser_Temp_HA_2")
        self.Input_RF_MON_HA_2 = QtWidgets.QLineEdit(self.groupBox_Un)
        self.Input_RF_MON_HA_2.setGeometry(QtCore.QRect(380, 130, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Input_RF_MON_HA_2.setFont(font)
        self.Input_RF_MON_HA_2.setObjectName("Input_RF_MON_HA_2")
        self.LAS_RF_HA_2 = QtWidgets.QLineEdit(self.groupBox_Un)
        self.LAS_RF_HA_2.setGeometry(QtCore.QRect(380, 160, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LAS_RF_HA_2.setFont(font)
        self.LAS_RF_HA_2.setObjectName("LAS_RF_HA_2")
        self.LSR_PDI_HA_2 = QtWidgets.QLineEdit(self.groupBox_Un)
        self.LSR_PDI_HA_2.setGeometry(QtCore.QRect(380, 250, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LSR_PDI_HA_2.setFont(font)
        self.LSR_PDI_HA_2.setObjectName("LSR_PDI_HA_2")
        self.FLSR_BIAS_HA_2 = QtWidgets.QLineEdit(self.groupBox_Un)
        self.FLSR_BIAS_HA_2.setGeometry(QtCore.QRect(380, 190, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.FLSR_BIAS_HA_2.setFont(font)
        self.FLSR_BIAS_HA_2.setObjectName("FLSR_BIAS_HA_2")
        self.RLSR_BIAS_HA_2 = QtWidgets.QLineEdit(self.groupBox_Un)
        self.RLSR_BIAS_HA_2.setGeometry(QtCore.QRect(380, 220, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.RLSR_BIAS_HA_2.setFont(font)
        self.RLSR_BIAS_HA_2.setObjectName("RLSR_BIAS_HA_2")
        self.ModuleTemp_HA_2 = QtWidgets.QLineEdit(self.groupBox_Un)
        self.ModuleTemp_HA_2.setGeometry(QtCore.QRect(380, 40, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ModuleTemp_HA_2.setFont(font)
        self.ModuleTemp_HA_2.setObjectName("ModuleTemp_HA_2")
        self.textEditBu = QtWidgets.QToolButton(self.groupBox_Un)
        self.textEditBu.setGeometry(QtCore.QRect(240, 290, 25, 19))
        self.textEditBu.setObjectName("textEditBu")
        self.CalibrateBu = QtWidgets.QPushButton(Dialog)
        self.CalibrateBu.setGeometry(QtCore.QRect(590, 360, 91, 23))
        self.CalibrateBu.setObjectName("CalibrateBu")
        self.v24_Ch = QtWidgets.QCheckBox(Dialog)
        self.v24_Ch.setGeometry(QtCore.QRect(890, 320, 21, 17))
        self.v24_Ch.setText("")
        self.v24_Ch.setChecked(True)
        self.v24_Ch.setObjectName("v24_Ch")
        self.defaultBu = QtWidgets.QPushButton(Dialog)
        self.defaultBu.setGeometry(QtCore.QRect(490, 360, 91, 23))
        self.defaultBu.setObjectName("defaultBu")

        self.retranslateUi(Dialog)
        self.exitBu.clicked.connect(Dialog.close)
        self.ModuleTemp_LA_2.returnPressed.connect(self.textEditBu.click)
        self.LSR_PDI_LA_2.returnPressed.connect(self.textEditBu.click)
        self.RLSR_BIAS_LA_2.returnPressed.connect(self.textEditBu.click)
        self.LAS_RF_LA_2.returnPressed.connect(self.textEditBu.click)
        self.Input_RF_MON_LA_2.returnPressed.connect(self.textEditBu.click)
        self.Laser_Temp_LA_2.returnPressed.connect(self.textEditBu.click)
        self.TEC_I_MON_LA_2.returnPressed.connect(self.textEditBu.click)
        self.LSR_PDI_LW_2.returnPressed.connect(self.textEditBu.click)
        self.RLSR_BIAS_LW_2.returnPressed.connect(self.textEditBu.click)
        self.FLSR_BIAS_LW_2.returnPressed.connect(self.textEditBu.click)
        self.Laser_Temp_LW_2.returnPressed.connect(self.textEditBu.click)
        self.LSR_PDI_HW_2.returnPressed.connect(self.textEditBu.click)
        self.RLSR_BIAS_HW_2.returnPressed.connect(self.textEditBu.click)
        self.FLSR_BIAS_HW_2.returnPressed.connect(self.textEditBu.click)
        self.Laser_Temp_HW_2.returnPressed.connect(self.textEditBu.click)
        self.LSR_PDI_HA_2.returnPressed.connect(self.textEditBu.click)
        self.RLSR_BIAS_HA_2.returnPressed.connect(self.textEditBu.click)
        self.FLSR_BIAS_HA_2.returnPressed.connect(self.textEditBu.click)
        self.LAS_RF_HA_2.returnPressed.connect(self.textEditBu.click)
        self.Input_RF_MON_HA_2.returnPressed.connect(self.textEditBu.click)
        self.Laser_Temp_HA_2.returnPressed.connect(self.textEditBu.click)
        self.TEC_I_MON_HA_2.returnPressed.connect(self.textEditBu.click)
        self.ModuleTemp_HA_2.returnPressed.connect(self.textEditBu.click)
        self.FLSR_BIAS_LA_2.returnPressed.connect(self.textEditBu.click)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Alarm"))
        Dialog.setWhatsThis(_translate("Dialog", "Alarm"))
        self.getFromBoardBu.setText(_translate("Dialog", "Get from Board"))
        self.saveToBoardBu.setText(_translate("Dialog", "Save to Board"))
        self.exitBu.setText(_translate("Dialog", "EXIT"))
        self.label_2.setText(_translate("Dialog", "Enable"))
        self.groupBoxDc.setTitle(_translate("Dialog", "DC"))
        self.label_9.setText(_translate("Dialog", "LSR-PDI (mv)"))
        self.label_7.setText(_translate("Dialog", "LAS-RF(mv)"))
        self.label_v5.setText(_translate("Dialog", "+5v MON (v)"))
        self.label_4.setText(_translate("Dialog", "Module Temp (mv)"))
        self.label.setText(_translate("Dialog", "LA        LW         OK        HW        HA    "))
        self.label_10.setText(_translate("Dialog", "RLSR-BIAS (mv)"))
        self.label_5.setText(_translate("Dialog", "Laser Temp (mv)"))
        self.label_11.setText(_translate("Dialog", "FLSR-BIAS (mv)"))
        self.label_6.setText(_translate("Dialog", "Input-RF-MON (mv)"))
        self.label_3.setText(_translate("Dialog", "TEC-I-MON (mv)"))
        self.label_VIN.setText(_translate("Dialog", "VIN MON (v)"))
        self.groupBox_Un.setTitle(_translate("Dialog", "Equivalency"))
        self.label_16.setText(_translate("Dialog", "Module Temp (C)"))
        self.label_19.setText(_translate("Dialog", "RLSR-BIAS (mA)"))
        self.label_20.setText(_translate("Dialog", "Laser Temp (C)"))
        self.label_21.setText(_translate("Dialog", "FLSR-BIAS (mA)"))
        self.label_23.setText(_translate("Dialog", "TEC-I-MON (mA)"))
        self.label_13.setText(_translate("Dialog", "Input-RF-MON (dBm)"))
        self.label_14.setText(_translate("Dialog", "LAS-RF(dBm)"))
        self.label_17.setText(_translate("Dialog", "LSR-PDI (mW)"))
        self.label_8.setText(_translate("Dialog", "LA          LW           OK          HW          HA    "))
        self.textEditBu.setText(_translate("Dialog", "..."))
        self.CalibrateBu.setText(_translate("Dialog", "Calibrate"))
        self.defaultBu.setText(_translate("Dialog", "Default"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

