

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(582, 283)
        Dialog.setSizeGripEnabled(True)
        self.exitBu = QtWidgets.QPushButton(Dialog)
        self.exitBu.setGeometry(QtCore.QRect(460, 240, 91, 21))
        self.exitBu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.exitBu.setStyleSheet("")
        self.exitBu.setObjectName("exitBu")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(420, 10, 151, 121))
        self.groupBox.setObjectName("groupBox")
        self.passwordEd = QtWidgets.QLineEdit(self.groupBox)
        self.passwordEd.setGeometry(QtCore.QRect(40, 80, 101, 20))
        self.passwordEd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEd.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordEd.setObjectName("passwordEd")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 80, 41, 21))
        self.label_9.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 40, 41, 21))
        self.label_10.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_10.setObjectName("label_10")
        self.userEd = QtWidgets.QLineEdit(self.groupBox)
        self.userEd.setGeometry(QtCore.QRect(40, 40, 101, 20))
        self.userEd.setAlignment(QtCore.Qt.AlignCenter)
        self.userEd.setObjectName("userEd")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 10, 391, 261))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 111, 21))
        self.label_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setObjectName("label_4")
        self.FirmwareRevisionEd = QtWidgets.QLineEdit(self.groupBox_2)
        self.FirmwareRevisionEd.setGeometry(QtCore.QRect(220, 180, 161, 20))
        self.FirmwareRevisionEd.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.FirmwareRevisionEd.setObjectName("FirmwareRevisionEd")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(20, 180, 111, 21))
        self.label_8.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_8.setObjectName("label_8")
        self.getFromBoardBu = QtWidgets.QPushButton(self.groupBox_2)
        self.getFromBoardBu.setGeometry(QtCore.QRect(20, 230, 91, 23))
        self.getFromBoardBu.setObjectName("getFromBoardBu")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(20, 120, 181, 21))
        self.label_6.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setObjectName("label_6")
        self.UnitSerialEd = QtWidgets.QLineEdit(self.groupBox_2)
        self.UnitSerialEd.setGeometry(QtCore.QRect(220, 60, 161, 20))
        self.UnitSerialEd.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.UnitSerialEd.setObjectName("UnitSerialEd")
        self.ModelNumberEd = QtWidgets.QLineEdit(self.groupBox_2)
        self.ModelNumberEd.setGeometry(QtCore.QRect(220, 30, 161, 20))
        self.ModelNumberEd.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ModelNumberEd.setObjectName("ModelNumberEd")
        self.ManufactureDateEd = QtWidgets.QLineEdit(self.groupBox_2)
        self.ManufactureDateEd.setGeometry(QtCore.QRect(220, 120, 161, 20))
        self.ManufactureDateEd.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ManufactureDateEd.setObjectName("ManufactureDateEd")
        self.saveToBoardBu = QtWidgets.QPushButton(self.groupBox_2)
        self.saveToBoardBu.setGeometry(QtCore.QRect(250, 230, 91, 23))
        self.saveToBoardBu.setObjectName("saveToBoardBu")
        self.LaserSerialEd = QtWidgets.QLineEdit(self.groupBox_2)
        self.LaserSerialEd.setGeometry(QtCore.QRect(220, 90, 161, 20))
        self.LaserSerialEd.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LaserSerialEd.setObjectName("LaserSerialEd")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 90, 111, 21))
        self.label_5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 150, 161, 21))
        self.label_7.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setObjectName("label_7")
        self.PCBNumberEd = QtWidgets.QLineEdit(self.groupBox_2)
        self.PCBNumberEd.setGeometry(QtCore.QRect(220, 150, 161, 20))
        self.PCBNumberEd.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.PCBNumberEd.setObjectName("PCBNumberEd")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 111, 21))
        self.label_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        self.exitBu.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Board Information"))
        self.exitBu.setText(_translate("Dialog", "EXIT"))
        self.groupBox.setTitle(_translate("Dialog", "Management"))
        self.label_9.setText(_translate("Dialog", "Pass"))
        self.label_10.setText(_translate("Dialog", "User"))
        self.groupBox_2.setTitle(_translate("Dialog", "Board Info"))
        self.label_4.setText(_translate("Dialog", "Model Number Info"))
        self.label_8.setText(_translate("Dialog", "Firmware Revision"))
        self.getFromBoardBu.setText(_translate("Dialog", "Get from Board"))
        self.label_6.setText(_translate("Dialog", "Manufacture Date (DDMMYYYY)"))
        self.saveToBoardBu.setText(_translate("Dialog", "Save to Board"))
        self.label_5.setText(_translate("Dialog", "Laser Serial Number"))
        self.label_7.setText(_translate("Dialog", "PCB Number (First 4-digits)"))
        self.label_3.setText(_translate("Dialog", "Unit Serial Number"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

