

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(310, 425)
        Dialog.setSizeGripEnabled(True)
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(220, 380, 75, 31))
        self.pushButton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_3.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 20, 82, 344))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comS = QtWidgets.QRadioButton(self.layoutWidget)
        self.comS.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.comS.setObjectName("comS")
        self.verticalLayout.addWidget(self.comS)
        self.comS_2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.comS_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.comS_2.setObjectName("comS_2")
        self.verticalLayout.addWidget(self.comS_2)
        self.comS_3 = QtWidgets.QRadioButton(self.layoutWidget)
        self.comS_3.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.comS_3.setObjectName("comS_3")
        self.verticalLayout.addWidget(self.comS_3)
        self.comS_4 = QtWidgets.QRadioButton(self.layoutWidget)
        self.comS_4.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.comS_4.setObjectName("comS_4")
        self.verticalLayout.addWidget(self.comS_4)
        self.comS_5 = QtWidgets.QRadioButton(self.layoutWidget)
        self.comS_5.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.comS_5.setChecked(True)
        self.comS_5.setObjectName("comS_5")
        self.verticalLayout.addWidget(self.comS_5)
        self.comS_7 = QtWidgets.QRadioButton(self.layoutWidget)
        self.comS_7.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.comS_7.setObjectName("comS_7")
        self.verticalLayout.addWidget(self.comS_7)
        self.comS_8 = QtWidgets.QRadioButton(self.layoutWidget)
        self.comS_8.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.comS_8.setObjectName("comS_8")
        self.verticalLayout.addWidget(self.comS_8)
        self.comS_6 = QtWidgets.QRadioButton(self.layoutWidget)
        self.comS_6.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.comS_6.setObjectName("comS_6")
        self.verticalLayout.addWidget(self.comS_6)
        self.comS_9 = QtWidgets.QRadioButton(self.layoutWidget)
        self.comS_9.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.comS_9.setObjectName("comS_9")
        self.verticalLayout.addWidget(self.comS_9)
        self.comS_11 = QtWidgets.QRadioButton(self.layoutWidget)
        self.comS_11.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.comS_11.setObjectName("comS_11")
        self.verticalLayout.addWidget(self.comS_11)
        self.comS_12 = QtWidgets.QRadioButton(self.layoutWidget)
        self.comS_12.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.comS_12.setObjectName("comS_12")
        self.verticalLayout.addWidget(self.comS_12)
        self.comS_10 = QtWidgets.QRadioButton(self.layoutWidget)
        self.comS_10.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.comS_10.setObjectName("comS_10")
        self.verticalLayout.addWidget(self.comS_10)

        self.retranslateUi(Dialog)
        self.pushButton_3.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "COM Port Select"))
        self.pushButton_3.setText(_translate("Dialog", "EXIT"))
        self.comS.setText(_translate("Dialog", "COM 1"))
        self.comS_2.setText(_translate("Dialog", "COM 2"))
        self.comS_3.setText(_translate("Dialog", "COM 3"))
        self.comS_4.setText(_translate("Dialog", "COM 4"))
        self.comS_5.setText(_translate("Dialog", "COM 5"))
        self.comS_7.setText(_translate("Dialog", "COM 6"))
        self.comS_8.setText(_translate("Dialog", "COM 7"))
        self.comS_6.setText(_translate("Dialog", "COM 8"))
        self.comS_9.setText(_translate("Dialog", "COM 9"))
        self.comS_11.setText(_translate("Dialog", "COM 10"))
        self.comS_12.setText(_translate("Dialog", "COM 11"))
        self.comS_10.setText(_translate("Dialog", "COM 12"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

