

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(998, 553)
        Dialog.setSizeGripEnabled(True)
        self.pushButton_8 = QtWidgets.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(350, 1052, 141, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(20, 80, 101, 31))
        self.checkBox.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.pushButton_9 = QtWidgets.QPushButton(Dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(620, 1040, 141, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(160, 490, 141, 31))
        self.pushButton_6.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(450, 490, 141, 31))
        self.pushButton_7.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(400, 20, 121, 31))
        self.label.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 131, 63);\n"
"")
        self.label.setObjectName("label")
        self.checkBox_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2.setGeometry(QtCore.QRect(150, 80, 91, 31))
        self.checkBox_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_3.setGeometry(QtCore.QRect(410, 80, 91, 31))
        self.checkBox_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_4.setGeometry(QtCore.QRect(280, 80, 101, 31))
        self.checkBox_4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_5.setGeometry(QtCore.QRect(910, 80, 91, 31))
        self.checkBox_5.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_6.setGeometry(QtCore.QRect(650, 80, 91, 31))
        self.checkBox_6.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.checkBox_6.setChecked(True)
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_7.setGeometry(QtCore.QRect(520, 80, 101, 31))
        self.checkBox_7.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.checkBox_7.setChecked(True)
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_8.setGeometry(QtCore.QRect(780, 80, 101, 31))
        self.checkBox_8.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.checkBox_8.setChecked(True)
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_9.setGeometry(QtCore.QRect(780, 180, 101, 31))
        self.checkBox_9.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.checkBox_9.setChecked(True)
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_10.setGeometry(QtCore.QRect(650, 180, 91, 31))
        self.checkBox_10.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.checkBox_10.setChecked(True)
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_11.setGeometry(QtCore.QRect(410, 180, 91, 31))
        self.checkBox_11.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.checkBox_11.setChecked(True)
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_12.setGeometry(QtCore.QRect(150, 180, 91, 31))
        self.checkBox_12.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.checkBox_12.setChecked(True)
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_13.setGeometry(QtCore.QRect(20, 180, 101, 31))
        self.checkBox_13.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.checkBox_13.setChecked(True)
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_14.setGeometry(QtCore.QRect(520, 180, 101, 31))
        self.checkBox_14.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.checkBox_14.setChecked(True)
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_15.setGeometry(QtCore.QRect(910, 180, 91, 31))
        self.checkBox_15.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.checkBox_15.setChecked(True)
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_16.setGeometry(QtCore.QRect(280, 180, 101, 31))
        self.checkBox_16.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.checkBox_16.setChecked(True)
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_17.setGeometry(QtCore.QRect(780, 300, 101, 31))
        self.checkBox_17.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.checkBox_17.setChecked(True)
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_18.setGeometry(QtCore.QRect(650, 300, 91, 31))
        self.checkBox_18.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.checkBox_18.setChecked(True)
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_19 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_19.setGeometry(QtCore.QRect(410, 300, 91, 31))
        self.checkBox_19.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.checkBox_19.setChecked(True)
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_20 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_20.setGeometry(QtCore.QRect(150, 300, 91, 31))
        self.checkBox_20.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.checkBox_20.setChecked(True)
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkBox_21 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_21.setGeometry(QtCore.QRect(20, 300, 101, 31))
        self.checkBox_21.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.checkBox_21.setChecked(True)
        self.checkBox_21.setObjectName("checkBox_21")
        self.checkBox_22 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_22.setGeometry(QtCore.QRect(520, 300, 101, 31))
        self.checkBox_22.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.checkBox_22.setChecked(True)
        self.checkBox_22.setObjectName("checkBox_22")
        self.checkBox_23 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_23.setGeometry(QtCore.QRect(910, 300, 91, 31))
        self.checkBox_23.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.checkBox_23.setChecked(True)
        self.checkBox_23.setObjectName("checkBox_23")
        self.checkBox_24 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_24.setGeometry(QtCore.QRect(280, 300, 101, 31))
        self.checkBox_24.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.checkBox_24.setChecked(True)
        self.checkBox_24.setObjectName("checkBox_24")
        self.checkBox_25 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_25.setGeometry(QtCore.QRect(20, 420, 91, 31))
        self.checkBox_25.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.checkBox_25.setChecked(True)
        self.checkBox_25.setObjectName("checkBox_25")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(784, 482, 131, 31))
        self.pushButton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_3.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Dialog)
        self.pushButton_3.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "DAC Configuration"))
        self.pushButton_8.setText(_translate("Dialog", "Save to file"))
        self.checkBox.setText(_translate("Dialog", "Attn"))
        self.pushButton_9.setText(_translate("Dialog", "Save to Board"))
        self.pushButton_6.setText(_translate("Dialog", "Save to file"))
        self.pushButton_7.setText(_translate("Dialog", "Save to Board"))
        self.label.setText(_translate("Dialog", "DAC Enable"))
        self.checkBox_2.setText(_translate("Dialog", "MpTiltAdj"))
        self.checkBox_3.setText(_translate("Dialog", "Vamp"))
        self.checkBox_4.setText(_translate("Dialog", "PeakAdjMp"))
        self.checkBox_5.setText(_translate("Dialog", "Res"))
        self.checkBox_6.setText(_translate("Dialog", "VSbs"))
        self.checkBox_7.setText(_translate("Dialog", "TpAttn"))
        self.checkBox_8.setText(_translate("Dialog", "VSbs"))
        self.checkBox_9.setText(_translate("Dialog", "Vclamp"))
        self.checkBox_10.setText(_translate("Dialog", "Vcso4"))
        self.checkBox_11.setText(_translate("Dialog", "Vctb"))
        self.checkBox_12.setText(_translate("Dialog", "Vxmod"))
        self.checkBox_13.setText(_translate("Dialog", "Vcso2"))
        self.checkBox_14.setText(_translate("Dialog", "Vctb3"))
        self.checkBox_15.setText(_translate("Dialog", "Vcso3"))
        self.checkBox_16.setText(_translate("Dialog", "ModBias"))
        self.checkBox_17.setText(_translate("Dialog", "Vadj"))
        self.checkBox_18.setText(_translate("Dialog", "Vadj"))
        self.checkBox_19.setText(_translate("Dialog", "AttnTpTiltAdj"))
        self.checkBox_20.setText(_translate("Dialog", "RlsrBias"))
        self.checkBox_21.setText(_translate("Dialog", "FlsrBias"))
        self.checkBox_22.setText(_translate("Dialog", "TpTiltAdj"))
        self.checkBox_23.setText(_translate("Dialog", "Res"))
        self.checkBox_24.setText(_translate("Dialog", "RlsrBias"))
        self.checkBox_25.setText(_translate("Dialog", "freq"))
        self.pushButton_3.setText(_translate("Dialog", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

