

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(828, 527)
        Dialog.setSizeGripEnabled(True)
        self.getFcDateBu = QtWidgets.QPushButton(Dialog)
        self.getFcDateBu.setGeometry(QtCore.QRect(520, 480, 75, 31))
        self.getFcDateBu.setObjectName("getFcDateBu")
        self.exitBu = QtWidgets.QPushButton(Dialog)
        self.exitBu.setGeometry(QtCore.QRect(640, 480, 75, 31))
        self.exitBu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.exitBu.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.exitBu.setObjectName("exitBu")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(1, 30, 421, 491))
        self.groupBox.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 101, 21))
        self.label.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.selChannelFC = QtWidgets.QComboBox(self.groupBox)
        self.selChannelFC.setGeometry(QtCore.QRect(140, 30, 151, 31))
        self.selChannelFC.setObjectName("selChannelFC")

        self.selChannelFC.addItem('Attn')
        self.selChannelFC.addItem('MpTiltAdj')
        self.selChannelFC.addItem('PeakAdjMp')
        self.selChannelFC.addItem('Vamp')
        self.selChannelFC.addItem('TpAttn')
        self.selChannelFC.addItem('VSbs')
        self.selChannelFC.addItem('Vxt')
        self.selChannelFC.addItem('Res1')

        self.selChannelFC.addItem('Vcso2')       
        self.selChannelFC.addItem('Vxmod')
        self.selChannelFC.addItem('ModBias')
        self.selChannelFC.addItem('Vctb')
        self.selChannelFC.addItem('Vctb3')
        self.selChannelFC.addItem('Vcso4')
        self.selChannelFC.addItem('Vclamp')
        self.selChannelFC.addItem('Vcso3')

        self.selChannelFC.addItem('FlsrBias')   
        self.selChannelFC.addItem('RlsrBias')
        self.selChannelFC.addItem('LsrTemp')
        self.selChannelFC.addItem('TpTiltAdj')
        self.selChannelFC.addItem('PeakAdjTp')
        self.selChannelFC.addItem('Vadj')
        self.selChannelFC.addItem('DitherCorr')
        self.selChannelFC.addItem('Res2')

        
        self.channelEnaCheck = QtWidgets.QCheckBox(self.groupBox)
        self.channelEnaCheck.setGeometry(QtCore.QRect(310, 20, 81, 41))
        self.channelEnaCheck.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.channelEnaCheck.setChecked(True)
        self.channelEnaCheck.setObjectName("channelEnaCheck")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(150, 140, 101, 31))
        self.label_3.setStyleSheet("color: rgb(0, 136, 65);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(300, 140, 81, 31))
        self.label_4.setStyleSheet("color: rgb(0, 136, 65);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.saveToBoardBu = QtWidgets.QPushButton(self.groupBox)
        self.saveToBoardBu.setGeometry(QtCore.QRect(280, 460, 121, 27))
        self.saveToBoardBu.setToolTipDuration(-8)
        self.saveToBoardBu.setObjectName("saveToBoardBu")
        self.getFromBoardBu = QtWidgets.QPushButton(self.groupBox)
        self.getFromBoardBu.setEnabled(True)
        self.getFromBoardBu.setGeometry(QtCore.QRect(140, 460, 121, 27))
        self.getFromBoardBu.setObjectName("getFromBoardBu")
        self.fcpd_5 = QtWidgets.QLineEdit(self.groupBox)
        self.fcpd_5.setGeometry(QtCore.QRect(280, 260, 101, 21))
        self.fcpd_5.setAlignment(QtCore.Qt.AlignCenter)
        self.fcpd_5.setObjectName("fcpd_5")
        self.fcpd_4 = QtWidgets.QLineEdit(self.groupBox)
        self.fcpd_4.setGeometry(QtCore.QRect(280, 290, 101, 21))
        self.fcpd_4.setAlignment(QtCore.Qt.AlignCenter)
        self.fcpd_4.setObjectName("fcpd_4")
        self.fcpd_3 = QtWidgets.QLineEdit(self.groupBox)
        self.fcpd_3.setGeometry(QtCore.QRect(280, 320, 101, 21))
        self.fcpd_3.setAlignment(QtCore.Qt.AlignCenter)
        self.fcpd_3.setObjectName("fcpd_3")
        self.fcpd_2 = QtWidgets.QLineEdit(self.groupBox)
        self.fcpd_2.setGeometry(QtCore.QRect(280, 350, 101, 21))
        self.fcpd_2.setAlignment(QtCore.Qt.AlignCenter)
        self.fcpd_2.setObjectName("fcpd_2")
        self.fcpd_1 = QtWidgets.QLineEdit(self.groupBox)
        self.fcpd_1.setGeometry(QtCore.QRect(280, 380, 101, 21))
        self.fcpd_1.setAlignment(QtCore.Qt.AlignCenter)
        self.fcpd_1.setObjectName("fcpd_1")
        self.fcpd_0 = QtWidgets.QLineEdit(self.groupBox)
        self.fcpd_0.setGeometry(QtCore.QRect(280, 410, 101, 21))
        self.fcpd_0.setAlignment(QtCore.Qt.AlignCenter)
        self.fcpd_0.setObjectName("fcpd_0")
        self.fcd_2 = QtWidgets.QLineEdit(self.groupBox)
        self.fcd_2.setGeometry(QtCore.QRect(150, 350, 101, 21))
        self.fcd_2.setAlignment(QtCore.Qt.AlignCenter)
        self.fcd_2.setObjectName("fcd_2")
        self.fcd_5 = QtWidgets.QLineEdit(self.groupBox)
        self.fcd_5.setGeometry(QtCore.QRect(150, 260, 101, 21))
        self.fcd_5.setAlignment(QtCore.Qt.AlignCenter)
        self.fcd_5.setObjectName("fcd_5")
        self.fcd_3 = QtWidgets.QLineEdit(self.groupBox)
        self.fcd_3.setGeometry(QtCore.QRect(150, 320, 101, 21))
        self.fcd_3.setAlignment(QtCore.Qt.AlignCenter)
        self.fcd_3.setObjectName("fcd_3")
        self.fcd_1 = QtWidgets.QLineEdit(self.groupBox)
        self.fcd_1.setGeometry(QtCore.QRect(150, 380, 101, 21))
        self.fcd_1.setAlignment(QtCore.Qt.AlignCenter)
        self.fcd_1.setObjectName("fcd_1")
        self.fcd_0 = QtWidgets.QLineEdit(self.groupBox)
        self.fcd_0.setGeometry(QtCore.QRect(150, 410, 101, 21))
        self.fcd_0.setAlignment(QtCore.Qt.AlignCenter)
        self.fcd_0.setObjectName("fcd_0")
        self.fcd_4 = QtWidgets.QLineEdit(self.groupBox)
        self.fcd_4.setGeometry(QtCore.QRect(150, 290, 101, 21))
        self.fcd_4.setAlignment(QtCore.Qt.AlignCenter)
        self.fcd_4.setObjectName("fcd_4")
        self.fcpd_6 = QtWidgets.QLineEdit(self.groupBox)
        self.fcpd_6.setGeometry(QtCore.QRect(280, 230, 101, 21))
        self.fcpd_6.setAlignment(QtCore.Qt.AlignCenter)
        self.fcpd_6.setObjectName("fcpd_6")
        self.fcd_6 = QtWidgets.QLineEdit(self.groupBox)
        self.fcd_6.setGeometry(QtCore.QRect(150, 230, 101, 21))
        self.fcd_6.setAlignment(QtCore.Qt.AlignCenter)
        self.fcd_6.setObjectName("fcd_6")
        self.fcd_7 = QtWidgets.QLineEdit(self.groupBox)
        self.fcd_7.setGeometry(QtCore.QRect(150, 200, 101, 21))
        self.fcd_7.setAlignment(QtCore.Qt.AlignCenter)
        self.fcd_7.setObjectName("fcd_7")
        self.fcpd_7 = QtWidgets.QLineEdit(self.groupBox)
        self.fcpd_7.setGeometry(QtCore.QRect(280, 200, 101, 21))
        self.fcpd_7.setAlignment(QtCore.Qt.AlignCenter)
        self.fcpd_7.setObjectName("fcpd_7")
        self.fibLenSpi = QtWidgets.QSpinBox(self.groupBox)
        self.fibLenSpi.setGeometry(QtCore.QRect(300, 85, 91, 31))
        self.fibLenSpi.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.fibLenSpi.setAlignment(QtCore.Qt.AlignCenter)
        self.fibLenSpi.setMaximum(160)
        self.fibLenSpi.setProperty("value", 10)
        self.fibLenSpi.setObjectName("fibLenSpi")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(20, 90, 101, 21))
        self.label_9.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.fibLenSli = QtWidgets.QSlider(self.groupBox)
        self.fibLenSli.setGeometry(QtCore.QRect(130, 90, 160, 22))
        self.fibLenSli.setStyleSheet(" QSlider::groove:horizontal {\n"
"     border: 1px solid #999999;\n"
"     height: 8px; /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
"     background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
"     margin: 2px 0;\n"
" }\n"
"\n"
" QSlider::handle:horizontal {\n"
"     background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"     border: 1px solid #5c5c5c;\n"
"     width: 18px;\n"
"     margin: -2px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
"     border-radius: 3px;\n"
" }")
        self.fibLenSli.setMaximum(160)
        self.fibLenSli.setProperty("value", 10)
        self.fibLenSli.setOrientation(QtCore.Qt.Horizontal)
        self.fibLenSli.setObjectName("fibLenSli")
        self.fcpd_8 = QtWidgets.QLineEdit(self.groupBox)
        self.fcpd_8.setGeometry(QtCore.QRect(280, 170, 101, 21))
        self.fcpd_8.setAlignment(QtCore.Qt.AlignCenter)
        self.fcpd_8.setObjectName("fcpd_8")
        self.fcd_8 = QtWidgets.QLineEdit(self.groupBox)
        self.fcd_8.setGeometry(QtCore.QRect(150, 170, 101, 21))
        self.fcd_8.setAlignment(QtCore.Qt.AlignCenter)
        self.fcd_8.setObjectName("fcd_8")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 170, 87, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.label_18)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        self.label_20.setObjectName("label_20")
        self.verticalLayout.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget)
        self.label_21.setObjectName("label_21")
        self.verticalLayout.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget)
        self.label_22.setObjectName("label_22")
        self.verticalLayout.addWidget(self.label_22)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget)
        self.label_26.setObjectName("label_26")
        self.verticalLayout.addWidget(self.label_26)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget)
        self.label_24.setObjectName("label_24")
        self.verticalLayout.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget)
        self.label_25.setObjectName("label_25")
        self.verticalLayout.addWidget(self.label_25)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(450, 40, 341, 241))
        self.widget.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 77, 37);")
        self.widget.setObjectName("widget")
        self.FcConfigBu = QtWidgets.QPushButton(Dialog)
        self.FcConfigBu.setGeometry(QtCore.QRect(0, 0, 75, 23))
        self.FcConfigBu.setObjectName("FcConfigBu")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(700, 300, 91, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(580, 300, 91, 21))
        self.label_11.setObjectName("label_11")
        self.fcCorrectionEdit = QtWidgets.QLineEdit(Dialog)
        self.fcCorrectionEdit.setGeometry(QtCore.QRect(700, 320, 71, 21))
        self.fcCorrectionEdit.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.fcCorrectionEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.fcCorrectionEdit.setObjectName("fcCorrectionEdit")
        self.dac25Edit = QtWidgets.QLineEdit(Dialog)
        self.dac25Edit.setGeometry(QtCore.QRect(580, 320, 71, 21))
        self.dac25Edit.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.dac25Edit.setAlignment(QtCore.Qt.AlignCenter)
        self.dac25Edit.setObjectName("dac25Edit")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(460, 300, 71, 21))
        self.label_16.setObjectName("label_16")
        self.FibLen = QtWidgets.QLineEdit(Dialog)
        self.FibLen.setGeometry(QtCore.QRect(460, 320, 71, 21))
        self.FibLen.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.FibLen.setAlignment(QtCore.Qt.AlignCenter)
        self.FibLen.setObjectName("FibLen")

        self.retranslateUi(Dialog)
        self.exitBu.clicked.connect(Dialog.close)
        self.fibLenSli.valueChanged['int'].connect(self.fibLenSpi.setValue)
        self.fibLenSpi.valueChanged['int'].connect(self.fibLenSli.setValue)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "FC Table"))
        self.getFcDateBu.setText(_translate("Dialog", "Get TC Data"))
        self.exitBu.setText(_translate("Dialog", "EXIT"))
        self.groupBox.setTitle(_translate("Dialog", "FC"))
        self.label.setText(_translate("Dialog", "Select a channel:"))
        self.channelEnaCheck.setText(_translate("Dialog", "Enable"))
        self.label_3.setText(_translate("Dialog", "Distance (km)"))
        self.label_4.setText(_translate("Dialog", "Data (mV)"))
        self.saveToBoardBu.setText(_translate("Dialog", "Save to Board"))
        self.getFromBoardBu.setText(_translate("Dialog", "Get from Board"))
        self.fcpd_5.setText(_translate("Dialog", "0"))
        self.fcpd_4.setText(_translate("Dialog", "0"))
        self.fcpd_3.setText(_translate("Dialog", "0"))
        self.fcpd_2.setText(_translate("Dialog", "0"))
        self.fcpd_1.setText(_translate("Dialog", "0"))
        self.fcpd_0.setText(_translate("Dialog", "0"))
        self.fcd_2.setText(_translate("Dialog", "40"))
        self.fcd_5.setText(_translate("Dialog", "100"))
        self.fcd_3.setText(_translate("Dialog", "60"))
        self.fcd_1.setText(_translate("Dialog", "20"))
        self.fcd_0.setText(_translate("Dialog", "0"))
        self.fcd_4.setText(_translate("Dialog", "80"))
        self.fcpd_6.setText(_translate("Dialog", "0"))
        self.fcd_6.setText(_translate("Dialog", "120"))
        self.fcd_7.setText(_translate("Dialog", "140"))
        self.fcpd_7.setText(_translate("Dialog", "0"))
        self.label_9.setText(_translate("Dialog", "Fiber Length (km)"))
        self.fcpd_8.setText(_translate("Dialog", "0"))
        self.fcd_8.setText(_translate("Dialog", "160"))
        self.label_18.setText(_translate("Dialog", "FC POINT 8"))
        self.label_17.setText(_translate("Dialog", "FC POINT 7"))
        self.label_19.setText(_translate("Dialog", "FC POINT 6"))
        self.label_20.setText(_translate("Dialog", "FC POINT 5"))
        self.label_21.setText(_translate("Dialog", "FC POINT 4"))
        self.label_22.setText(_translate("Dialog", "FC POINT 3"))
        self.label_26.setText(_translate("Dialog", "FC POINT 2"))
        self.label_24.setText(_translate("Dialog", "FC POINT 1"))
        self.label_25.setText(_translate("Dialog", "FC POINT 0"))
        self.FcConfigBu.setText(_translate("Dialog", "Configure"))
        self.label_10.setText(_translate("Dialog", "FC Correction(mv)"))
        self.label_11.setText(_translate("Dialog", "DAC(mv) @ 25 C"))
        self.fcCorrectionEdit.setText(_translate("Dialog", "0"))
        self.dac25Edit.setText(_translate("Dialog", "0"))
        self.label_16.setText(_translate("Dialog", "Fiber Length"))
        self.FibLen.setText(_translate("Dialog", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

