

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(989, 318)
        Dialog.setSizeGripEnabled(True)
        self.RlsrBias = QtWidgets.QCheckBox(Dialog)
        self.RlsrBias.setGeometry(QtCore.QRect(160, 180, 91, 31))
        self.RlsrBias.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.RlsrBias.setChecked(True)
        self.RlsrBias.setObjectName("RlsrBias")
        self.LsrTemp = QtWidgets.QCheckBox(Dialog)
        self.LsrTemp.setGeometry(QtCore.QRect(280, 180, 101, 31))
        self.LsrTemp.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.LsrTemp.setChecked(True)
        self.LsrTemp.setObjectName("LsrTemp")
        self.PeakAdjMp = QtWidgets.QCheckBox(Dialog)
        self.PeakAdjMp.setGeometry(QtCore.QRect(280, 60, 101, 31))
        self.PeakAdjMp.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.PeakAdjMp.setChecked(True)
        self.PeakAdjMp.setObjectName("PeakAdjMp")
        self.TpAttn = QtWidgets.QCheckBox(Dialog)
        self.TpAttn.setGeometry(QtCore.QRect(520, 60, 101, 31))
        self.TpAttn.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.TpAttn.setChecked(True)
        self.TpAttn.setObjectName("TpAttn")
        self.Vclamp = QtWidgets.QCheckBox(Dialog)
        self.Vclamp.setGeometry(QtCore.QRect(760, 120, 101, 31))
        self.Vclamp.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.Vclamp.setChecked(True)
        self.Vclamp.setObjectName("Vclamp")
        self.MpTiltAdj = QtWidgets.QCheckBox(Dialog)
        self.MpTiltAdj.setGeometry(QtCore.QRect(160, 60, 91, 31))
        self.MpTiltAdj.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.MpTiltAdj.setChecked(True)
        self.MpTiltAdj.setObjectName("MpTiltAdj")
        self.Res1 = QtWidgets.QCheckBox(Dialog)
        self.Res1.setGeometry(QtCore.QRect(880, 60, 91, 31))
        self.Res1.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.Res1.setChecked(True)
        self.Res1.setObjectName("Res1")
        self.saveToBoardBu = QtWidgets.QPushButton(Dialog)
        self.saveToBoardBu.setGeometry(QtCore.QRect(580, 270, 111, 31))
        self.saveToBoardBu.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.saveToBoardBu.setObjectName("saveToBoardBu")
        self.disableAllBu = QtWidgets.QPushButton(Dialog)
        self.disableAllBu.setGeometry(QtCore.QRect(180, 270, 111, 31))
        self.disableAllBu.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.disableAllBu.setObjectName("disableAllBu")
        self.FlsrBias = QtWidgets.QCheckBox(Dialog)
        self.FlsrBias.setGeometry(QtCore.QRect(40, 180, 101, 31))
        self.FlsrBias.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.FlsrBias.setChecked(True)
        self.FlsrBias.setObjectName("FlsrBias")
        self.ModBias = QtWidgets.QCheckBox(Dialog)
        self.ModBias.setGeometry(QtCore.QRect(280, 120, 101, 31))
        self.ModBias.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.ModBias.setChecked(True)
        self.ModBias.setObjectName("ModBias")
        self.Vxt = QtWidgets.QCheckBox(Dialog)
        self.Vxt.setGeometry(QtCore.QRect(760, 60, 101, 31))
        self.Vxt.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.Vxt.setChecked(True)
        self.Vxt.setObjectName("Vxt")
        self.Vadj = QtWidgets.QCheckBox(Dialog)
        self.Vadj.setGeometry(QtCore.QRect(640, 180, 91, 31))
        self.Vadj.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.Vadj.setChecked(True)
        self.Vadj.setObjectName("Vadj")
        self.Vcso2 = QtWidgets.QCheckBox(Dialog)
        self.Vcso2.setGeometry(QtCore.QRect(40, 120, 101, 31))
        self.Vcso2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.Vcso2.setChecked(True)
        self.Vcso2.setObjectName("Vcso2")
        self.PeakAdjTp = QtWidgets.QCheckBox(Dialog)
        self.PeakAdjTp.setGeometry(QtCore.QRect(520, 180, 101, 31))
        self.PeakAdjTp.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.PeakAdjTp.setChecked(True)
        self.PeakAdjTp.setObjectName("PeakAdjTp")
        self.Vcso3 = QtWidgets.QCheckBox(Dialog)
        self.Vcso3.setGeometry(QtCore.QRect(880, 120, 91, 31))
        self.Vcso3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.Vcso3.setChecked(True)
        self.Vcso3.setObjectName("Vcso3")
        self.Attn = QtWidgets.QCheckBox(Dialog)
        self.Attn.setGeometry(QtCore.QRect(40, 60, 101, 31))
        self.Attn.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.Attn.setChecked(True)
        self.Attn.setObjectName("Attn")
        self.enableAllBu = QtWidgets.QPushButton(Dialog)
        self.enableAllBu.setGeometry(QtCore.QRect(50, 270, 111, 31))
        self.enableAllBu.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.enableAllBu.setObjectName("enableAllBu")
        self.VSbs = QtWidgets.QCheckBox(Dialog)
        self.VSbs.setGeometry(QtCore.QRect(640, 60, 91, 31))
        self.VSbs.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.VSbs.setChecked(True)
        self.VSbs.setObjectName("VSbs")
        self.TpTiltAdj = QtWidgets.QCheckBox(Dialog)
        self.TpTiltAdj.setGeometry(QtCore.QRect(400, 180, 91, 31))
        self.TpTiltAdj.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.TpTiltAdj.setChecked(True)
        self.TpTiltAdj.setObjectName("TpTiltAdj")
        self.Vctb = QtWidgets.QCheckBox(Dialog)
        self.Vctb.setGeometry(QtCore.QRect(400, 120, 91, 31))
        self.Vctb.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.Vctb.setChecked(True)
        self.Vctb.setObjectName("Vctb")
        self.Vctb3 = QtWidgets.QCheckBox(Dialog)
        self.Vctb3.setGeometry(QtCore.QRect(520, 120, 101, 31))
        self.Vctb3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.Vctb3.setChecked(True)
        self.Vctb3.setObjectName("Vctb3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(420, 0, 121, 31))
        self.label.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 131, 63);\n"
"")
        self.label.setObjectName("label")
        self.Res2 = QtWidgets.QCheckBox(Dialog)
        self.Res2.setGeometry(QtCore.QRect(880, 180, 91, 31))
        self.Res2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.Res2.setChecked(True)
        self.Res2.setObjectName("Res2")
        self.closeBu = QtWidgets.QPushButton(Dialog)
        self.closeBu.setGeometry(QtCore.QRect(810, 270, 111, 31))
        self.closeBu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.closeBu.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.closeBu.setObjectName("closeBu")
        self.Vcso4 = QtWidgets.QCheckBox(Dialog)
        self.Vcso4.setGeometry(QtCore.QRect(640, 120, 91, 31))
        self.Vcso4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.Vcso4.setChecked(True)
        self.Vcso4.setObjectName("Vcso4")
        self.Vamp = QtWidgets.QCheckBox(Dialog)
        self.Vamp.setGeometry(QtCore.QRect(400, 60, 91, 31))
        self.Vamp.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.Vamp.setChecked(True)
        self.Vamp.setObjectName("Vamp")
        self.getFromBoardBu = QtWidgets.QPushButton(Dialog)
        self.getFromBoardBu.setGeometry(QtCore.QRect(450, 270, 111, 31))
        self.getFromBoardBu.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.getFromBoardBu.setObjectName("getFromBoardBu")
        self.Vxmod = QtWidgets.QCheckBox(Dialog)
        self.Vxmod.setGeometry(QtCore.QRect(160, 120, 91, 31))
        self.Vxmod.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.Vxmod.setChecked(True)
        self.Vxmod.setObjectName("Vxmod")
        self.DitherCorr = QtWidgets.QCheckBox(Dialog)
        self.DitherCorr.setGeometry(QtCore.QRect(760, 180, 101, 31))
        self.DitherCorr.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.DitherCorr.setChecked(True)
        self.DitherCorr.setObjectName("DitherCorr")

        self.retranslateUi(Dialog)
        self.closeBu.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "FC Enable"))
        self.RlsrBias.setText(_translate("Dialog", "RlsrBias"))
        self.LsrTemp.setText(_translate("Dialog", "LsrTemp"))
        self.PeakAdjMp.setText(_translate("Dialog", "PeakAdjMp"))
        self.TpAttn.setText(_translate("Dialog", "TpAttn"))
        self.Vclamp.setText(_translate("Dialog", "Vclamp"))
        self.MpTiltAdj.setText(_translate("Dialog", "MpTiltAdj"))
        self.Res1.setText(_translate("Dialog", "Res"))
        self.saveToBoardBu.setText(_translate("Dialog", "Save to Board"))
        self.disableAllBu.setText(_translate("Dialog", "Disable All"))
        self.FlsrBias.setText(_translate("Dialog", "FlsrBias"))
        self.ModBias.setText(_translate("Dialog", "ModBias"))
        self.Vxt.setText(_translate("Dialog", "Vxt"))
        self.Vadj.setText(_translate("Dialog", "Vadj"))
        self.Vcso2.setText(_translate("Dialog", "Vcso2"))
        self.PeakAdjTp.setText(_translate("Dialog", "PeakAdjTp"))
        self.Vcso3.setText(_translate("Dialog", "Vcso3"))
        self.Attn.setText(_translate("Dialog", "Attn"))
        self.enableAllBu.setText(_translate("Dialog", "Enable All"))
        self.VSbs.setText(_translate("Dialog", "VSbs"))
        self.TpTiltAdj.setText(_translate("Dialog", "TpTiltAdj"))
        self.Vctb.setText(_translate("Dialog", "Vctb"))
        self.Vctb3.setText(_translate("Dialog", "Vctb3"))
        self.label.setText(_translate("Dialog", "FC Enable"))
        self.Res2.setText(_translate("Dialog", "Res"))
        self.closeBu.setText(_translate("Dialog", "EXIT"))
        self.Vcso4.setText(_translate("Dialog", "Vcso4"))
        self.Vamp.setText(_translate("Dialog", "Vamp"))
        self.getFromBoardBu.setText(_translate("Dialog", "Get fromBoard"))
        self.Vxmod.setText(_translate("Dialog", "Vxmod"))
        self.DitherCorr.setText(_translate("Dialog", "DitherCorr"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

