

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(752, 480)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(400, 40, 341, 241))
        self.widget.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 77, 37);")
        self.widget.setObjectName("widget")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(520, 300, 91, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(640, 300, 91, 21))
        self.label_10.setObjectName("label_10")
        self.exitBu = QtWidgets.QPushButton(Dialog)
        self.exitBu.setGeometry(QtCore.QRect(650, 430, 75, 31))
        self.exitBu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.exitBu.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.exitBu.setObjectName("exitBu")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(0, 30, 381, 441))
        self.groupBox.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 101, 21))
        self.label.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.selChannelTC = QtWidgets.QComboBox(self.groupBox)
        self.selChannelTC.setGeometry(QtCore.QRect(120, 30, 151, 31))
        self.selChannelTC.setObjectName("selChannelTC")

        self.selChannelTC.addItem('Attn')
        self.selChannelTC.addItem('MpTiltAdj')
        self.selChannelTC.addItem('PeakAdjMp')
        self.selChannelTC.addItem('Vamp')
        self.selChannelTC.addItem('TpAttn')
        self.selChannelTC.addItem('VSbs')
        self.selChannelTC.addItem('Vxt')
        self.selChannelTC.addItem('Res1')

        self.selChannelTC.addItem('Vcso2')       
        self.selChannelTC.addItem('Vxmod')
        self.selChannelTC.addItem('ModBias')
        self.selChannelTC.addItem('Vctb')
        self.selChannelTC.addItem('Vctb3')
        self.selChannelTC.addItem('Vcso4')
        self.selChannelTC.addItem('Vclamp')
        self.selChannelTC.addItem('Vcso3')

        self.selChannelTC.addItem('FlsrBias')   
        self.selChannelTC.addItem('RlsrBias')
        self.selChannelTC.addItem('LsrTemp')
        self.selChannelTC.addItem('TpTiltAdj')
        self.selChannelTC.addItem('PeakAdjTp')
        self.selChannelTC.addItem('Vadj')
        self.selChannelTC.addItem('DitherCorr')
        self.selChannelTC.addItem(' Dither-Tune')




        
        self.channelEnaCheck = QtWidgets.QCheckBox(self.groupBox)
        self.channelEnaCheck.setGeometry(QtCore.QRect(290, 20, 71, 41))
        self.channelEnaCheck.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.channelEnaCheck.setChecked(True)
        self.channelEnaCheck.setObjectName("channelEnaCheck")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(150, 80, 101, 31))
        self.label_3.setStyleSheet("color: rgb(0, 136, 65);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(280, 80, 81, 31))
        self.label_4.setStyleSheet("color: rgb(0, 136, 65);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.saveToBoardBu = QtWidgets.QPushButton(self.groupBox)
        self.saveToBoardBu.setGeometry(QtCore.QRect(160, 400, 121, 27))
        self.saveToBoardBu.setToolTipDuration(-8)
        self.saveToBoardBu.setObjectName("saveToBoardBu")
        self.getFromBoardBu = QtWidgets.QPushButton(self.groupBox)
        self.getFromBoardBu.setEnabled(True)
        self.getFromBoardBu.setGeometry(QtCore.QRect(20, 400, 121, 27))
        self.getFromBoardBu.setObjectName("getFromBoardBu")
        self.tcpd_8 = QtWidgets.QLineEdit(self.groupBox)
        self.tcpd_8.setGeometry(QtCore.QRect(262, 120, 101, 21))
        self.tcpd_8.setAlignment(QtCore.Qt.AlignCenter)
        self.tcpd_8.setObjectName("tcpd_8")
        self.tcpd_7 = QtWidgets.QLineEdit(self.groupBox)
        self.tcpd_7.setGeometry(QtCore.QRect(260, 150, 101, 21))
        self.tcpd_7.setAlignment(QtCore.Qt.AlignCenter)
        self.tcpd_7.setObjectName("tcpd_7")
        self.tcpd_6 = QtWidgets.QLineEdit(self.groupBox)
        self.tcpd_6.setGeometry(QtCore.QRect(262, 180, 101, 21))
        self.tcpd_6.setAlignment(QtCore.Qt.AlignCenter)
        self.tcpd_6.setObjectName("tcpd_6")
        self.tcpd_5 = QtWidgets.QLineEdit(self.groupBox)
        self.tcpd_5.setGeometry(QtCore.QRect(260, 210, 101, 21))
        self.tcpd_5.setAlignment(QtCore.Qt.AlignCenter)
        self.tcpd_5.setObjectName("tcpd_5")
        self.tcpd_4 = QtWidgets.QLineEdit(self.groupBox)
        self.tcpd_4.setGeometry(QtCore.QRect(260, 240, 101, 21))
        self.tcpd_4.setAlignment(QtCore.Qt.AlignCenter)
        self.tcpd_4.setObjectName("tcpd_4")
        self.tcpd_3 = QtWidgets.QLineEdit(self.groupBox)
        self.tcpd_3.setGeometry(QtCore.QRect(260, 270, 101, 21))
        self.tcpd_3.setAlignment(QtCore.Qt.AlignCenter)
        self.tcpd_3.setObjectName("tcpd_3")
        self.tcpd_2 = QtWidgets.QLineEdit(self.groupBox)
        self.tcpd_2.setGeometry(QtCore.QRect(260, 300, 101, 21))
        self.tcpd_2.setAlignment(QtCore.Qt.AlignCenter)
        self.tcpd_2.setObjectName("tcpd_2")
        self.tcpd_1 = QtWidgets.QLineEdit(self.groupBox)
        self.tcpd_1.setGeometry(QtCore.QRect(260, 330, 101, 21))
        self.tcpd_1.setAlignment(QtCore.Qt.AlignCenter)
        self.tcpd_1.setObjectName("tcpd_1")
        self.tcpd_0 = QtWidgets.QLineEdit(self.groupBox)
        self.tcpd_0.setGeometry(QtCore.QRect(260, 360, 101, 21))
        self.tcpd_0.setAlignment(QtCore.Qt.AlignCenter)
        self.tcpd_0.setObjectName("tcpd_0")
        self.tcpt_8 = QtWidgets.QLineEdit(self.groupBox)
        self.tcpt_8.setGeometry(QtCore.QRect(140, 120, 91, 20))
        self.tcpt_8.setAlignment(QtCore.Qt.AlignCenter)
        self.tcpt_8.setObjectName("tcpt_8")
        self.tcpt_7 = QtWidgets.QLineEdit(self.groupBox)
        self.tcpt_7.setGeometry(QtCore.QRect(140, 150, 91, 20))
        self.tcpt_7.setAlignment(QtCore.Qt.AlignCenter)
        self.tcpt_7.setObjectName("tcpt_7")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 120, 89, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.label_18)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        self.label_20.setObjectName("label_20")
        self.verticalLayout.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget)
        self.label_21.setObjectName("label_21")
        self.verticalLayout.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget)
        self.label_22.setObjectName("label_22")
        self.verticalLayout.addWidget(self.label_22)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget)
        self.label_26.setObjectName("label_26")
        self.verticalLayout.addWidget(self.label_26)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget)
        self.label_24.setObjectName("label_24")
        self.verticalLayout.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget)
        self.label_25.setObjectName("label_25")
        self.verticalLayout.addWidget(self.label_25)
        self.tcpt_9 = QtWidgets.QLineEdit(self.groupBox)
        self.tcpt_9.setGeometry(QtCore.QRect(140, 210, 91, 20))
        self.tcpt_9.setAlignment(QtCore.Qt.AlignCenter)
        self.tcpt_9.setObjectName("tcpt_9")
        self.tcpt_6 = QtWidgets.QLineEdit(self.groupBox)
        self.tcpt_6.setGeometry(QtCore.QRect(140, 180, 91, 20))
        self.tcpt_6.setAlignment(QtCore.Qt.AlignCenter)
        self.tcpt_6.setObjectName("tcpt_6")
        self.tcpt_3 = QtWidgets.QLineEdit(self.groupBox)
        self.tcpt_3.setGeometry(QtCore.QRect(140, 270, 91, 20))
        self.tcpt_3.setAlignment(QtCore.Qt.AlignCenter)
        self.tcpt_3.setObjectName("tcpt_3")
        self.tcpt_4 = QtWidgets.QLineEdit(self.groupBox)
        self.tcpt_4.setGeometry(QtCore.QRect(140, 240, 91, 20))
        self.tcpt_4.setAlignment(QtCore.Qt.AlignCenter)
        self.tcpt_4.setObjectName("tcpt_4")
        self.tcpt_2 = QtWidgets.QLineEdit(self.groupBox)
        self.tcpt_2.setGeometry(QtCore.QRect(140, 300, 91, 20))
        self.tcpt_2.setAlignment(QtCore.Qt.AlignCenter)
        self.tcpt_2.setObjectName("tcpt_2")
        self.tcpt_1 = QtWidgets.QLineEdit(self.groupBox)
        self.tcpt_1.setGeometry(QtCore.QRect(140, 330, 91, 20))
        self.tcpt_1.setAlignment(QtCore.Qt.AlignCenter)
        self.tcpt_1.setObjectName("tcpt_1")
        self.tcpt_0 = QtWidgets.QLineEdit(self.groupBox)
        self.tcpt_0.setGeometry(QtCore.QRect(140, 360, 91, 20))
        self.tcpt_0.setAlignment(QtCore.Qt.AlignCenter)
        self.tcpt_0.setObjectName("tcpt_0")
        self.getTcDateBu = QtWidgets.QPushButton(Dialog)
        self.getTcDateBu.setGeometry(QtCore.QRect(560, 430, 75, 31))
        self.getTcDateBu.setObjectName("getTcDateBu")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(400, 300, 71, 21))
        self.label_8.setObjectName("label_8")
        self.TcConfigBu = QtWidgets.QPushButton(Dialog)
        self.TcConfigBu.setGeometry(QtCore.QRect(0, 0, 75, 23))
        self.TcConfigBu.setObjectName("TcConfigBu")
        self.moduleTemEdit = QtWidgets.QLineEdit(Dialog)
        self.moduleTemEdit.setGeometry(QtCore.QRect(400, 320, 71, 20))
        self.moduleTemEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.moduleTemEdit.setObjectName("moduleTemEdit")
        self.dac25Edit = QtWidgets.QLineEdit(Dialog)
        self.dac25Edit.setGeometry(QtCore.QRect(520, 320, 71, 20))
        self.dac25Edit.setAlignment(QtCore.Qt.AlignCenter)
        self.dac25Edit.setObjectName("dac25Edit")
        self.tcCorrectionEdit = QtWidgets.QLineEdit(Dialog)
        self.tcCorrectionEdit.setGeometry(QtCore.QRect(640, 320, 71, 20))
        self.tcCorrectionEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.tcCorrectionEdit.setObjectName("tcCorrectionEdit")
        self.pointSetBu = QtWidgets.QPushButton(Dialog)
        self.pointSetBu.setGeometry(QtCore.QRect(70, 0, 75, 23))
        self.pointSetBu.setObjectName("pointSetBu")
        self.pointSetCo = QtWidgets.QComboBox(Dialog)
        self.pointSetCo.setGeometry(QtCore.QRect(120, 0, 71, 21))
        self.pointSetCo.setObjectName("pointSetCo")



        self.retranslateUi(Dialog)
        self.exitBu.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "TC Table"))
        self.label_9.setText(_translate("Dialog", "DAC(mv) @ 25 C"))
        self.label_10.setText(_translate("Dialog", "tc Correction(mv)"))
        self.exitBu.setText(_translate("Dialog", "EXIT"))
        self.groupBox.setTitle(_translate("Dialog", "TC"))
        self.label.setText(_translate("Dialog", "Select a channel:"))
        self.channelEnaCheck.setText(_translate("Dialog", "Enable"))
        self.label_3.setText(_translate("Dialog", "Temp (C)"))
        self.label_4.setText(_translate("Dialog", "Data (mV)"))
        self.saveToBoardBu.setText(_translate("Dialog", "Save to Board"))
        self.getFromBoardBu.setText(_translate("Dialog", "Get from Board"))
        self.tcpd_8.setText(_translate("Dialog", "0"))
        self.tcpd_7.setText(_translate("Dialog", "0"))
        self.tcpd_6.setText(_translate("Dialog", "0"))
        self.tcpd_5.setText(_translate("Dialog", "0"))
        self.tcpd_4.setText(_translate("Dialog", "0"))
        self.tcpd_3.setText(_translate("Dialog", "0"))
        self.tcpd_2.setText(_translate("Dialog", "0"))
        self.tcpd_1.setText(_translate("Dialog", "0"))
        self.tcpd_0.setText(_translate("Dialog", "0"))
        self.tcpt_8.setText(_translate("Dialog", "70"))
        self.tcpt_7.setText(_translate("Dialog", "60"))
        self.label_18.setText(_translate("Dialog", "TC POINT 8"))
        self.label_17.setText(_translate("Dialog", "TC POINT 7"))
        self.label_19.setText(_translate("Dialog", "TC POINT 6"))
        self.label_20.setText(_translate("Dialog", "TC POINT 5"))
        self.label_21.setText(_translate("Dialog", "TC POINT 4"))
        self.label_22.setText(_translate("Dialog", "TC POINT 3"))
        self.label_26.setText(_translate("Dialog", "TC POINT 2"))
        self.label_24.setText(_translate("Dialog", "TC POINT 1"))
        self.label_25.setText(_translate("Dialog", "TC POINT 0"))
        self.tcpt_9.setText(_translate("Dialog", "40"))
        self.tcpt_6.setText(_translate("Dialog", "50"))
        self.tcpt_3.setText(_translate("Dialog", "20"))
        self.tcpt_4.setText(_translate("Dialog", "30"))
        self.tcpt_2.setText(_translate("Dialog", "10"))
        self.tcpt_1.setText(_translate("Dialog", "0"))
        self.tcpt_0.setText(_translate("Dialog", "-10"))
        self.getTcDateBu.setText(_translate("Dialog", "Get TC Data"))
        self.label_8.setText(_translate("Dialog", "Module Temp"))
        self.TcConfigBu.setText(_translate("Dialog", "Configure"))
        self.pointSetBu.setText(_translate("Dialog", "Point Set"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

